const GRAMMATICAL_NUMBER_QUESTIONS = {
  beginner: [
    // 1-10: Regular Plurals (-s)
    { question: "What is the plural of 'cat'?", choices: ["cates", "cats", "catss", "catties"], correctIndex: 1, explanation: "For most regular nouns, we simply add 's' to the end." },
    { question: "What is the plural of 'book'?", choices: ["bookes", "books", "bookies", "book"], correctIndex: 1, explanation: "Just add 's' to form the plural of 'book'." },
    { question: "What is the plural of 'dog'?", choices: ["dogs", "doges", "doggies", "doggs"], correctIndex: 0, explanation: "Add 's' to regular nouns like 'dog'." },
    { question: "What is the plural of 'apple'?", choices: ["apples", "applies", "applees", "appless"], correctIndex: 0, explanation: "Simply add 's' to words ending in 'e' like 'apple'." },
    { question: "What is the plural of 'car'?", choices: ["carrs", "cares", "cars", "caries"], correctIndex: 2, explanation: "Add 's' to 'car' to make it plural." },
    { question: "What is the plural of 'tree'?", choices: ["trees", "treeses", "trese", "treies"], correctIndex: 0, explanation: "Add 's' to 'tree'." },
    { question: "What is the plural of 'table'?", choices: ["tabless", "tables", "tablies", "tabels"], correctIndex: 1, explanation: "Add 's' to 'table'." },
    { question: "What is the plural of 'girl'?", choices: ["girles", "girls", "girlys", "girless"], correctIndex: 1, explanation: "Add 's' to 'girl'." },
    { question: "What is the plural of 'pencil'?", choices: ["penciles", "pencill", "pencils", "pencillies"], correctIndex: 2, explanation: "Add 's' to 'pencil'." },
    { question: "What is the plural of 'cup'?", choices: ["cupes", "cups", "cupps", "cupies"], correctIndex: 1, explanation: "Add 's' to 'cup'." },

    // 11-20: Plurals ending in -es (s, x, z, ch, sh)
    { question: "What is the plural of 'box'?", choices: ["boxs", "boxes", "boxies", "boxses"], correctIndex: 1, explanation: "Nouns ending in 'x' usually take '-es' in the plural." },
    { question: "What is the plural of 'bus'?", choices: ["buss", "buses", "busies", "buse"], correctIndex: 1, explanation: "Nouns ending in 's' take '-es'." },
    { question: "What is the plural of 'watch'?", choices: ["watchs", "watches", "watchies", "watch"], correctIndex: 1, explanation: "Nouns ending in 'ch' take '-es'." },
    { question: "What is the plural of 'brush'?", choices: ["brushs", "brushes", "brushies", "brushse"], correctIndex: 1, explanation: "Nouns ending in 'sh' take '-es'." },
    { question: "What is the plural of 'glass'?", choices: ["glass", "glases", "glasses", "glassies"], correctIndex: 2, explanation: "Nouns ending in 'ss' take '-es'." },
    { question: "What is the plural of 'fox'?", choices: ["foxs", "foxes", "foxies", "foxen"], correctIndex: 1, explanation: "Words ending in 'x' need '-es' to be plural." },
    { question: "What is the plural of 'dish'?", choices: ["dishs", "dishes", "dishies", "dishess"], correctIndex: 1, explanation: "Words ending in 'sh' add '-es'." },
    { question: "What is the plural of 'church'?", choices: ["churchs", "churches", "churchies", "chirches"], correctIndex: 1, explanation: "Words ending in 'ch' add '-es'." },
    { question: "What is the plural of 'dress'?", choices: ["dreses", "dresses", "dresss", "dressies"], correctIndex: 1, explanation: "Words ending in 'ss' add '-es'." },
    { question: "What is the plural of 'class'?", choices: ["classes", "classs", "classies", "clases"], correctIndex: 0, explanation: "Words ending in 'ss' add '-es'." },

    // 21-30: Plurals ending in -y (Consonant + y vs Vowel + y)
    { question: "What is the plural of 'baby'?", choices: ["babys", "babies", "babyes", "babys"], correctIndex: 1, explanation: "If a word ends in a consonant + y, change 'y' to 'i' and add 'es'." },
    { question: "What is the plural of 'city'?", choices: ["citys", "cities", "cityes", "citties"], correctIndex: 1, explanation: "Consonant + y (t+y) becomes 'ies'." },
    { question: "What is the plural of 'boy'?", choices: ["boies", "boys", "boyes", "boies"], correctIndex: 1, explanation: "If a word ends in a vowel + y (o+y), just add 's'." },
    { question: "What is the plural of 'toy'?", choices: ["toys", "toies", "toyes", "toyies"], correctIndex: 0, explanation: "Vowel + y (o+y), just add 's'." },
    { question: "What is the plural of 'lady'?", choices: ["ladys", "ladies", "ladyes", "ladees"], correctIndex: 1, explanation: "Consonant + y (d+y) becomes 'ies'." },
    { question: "What is the plural of 'party'?", choices: ["partys", "parties", "partyes", "partees"], correctIndex: 1, explanation: "Consonant + y becomes 'ies'." },
    { question: "What is the plural of 'key'?", choices: ["kies", "keys", "keyes", "keies"], correctIndex: 1, explanation: "Vowel + y (e+y), just add 's'." },
    { question: "What is the plural of 'day'?", choices: ["daies", "days", "dayes", "dais"], correctIndex: 1, explanation: "Vowel + y, just add 's'." },
    { question: "What is the plural of 'fly' (insect)?", choices: ["flys", "flies", "flyes", "flyies"], correctIndex: 1, explanation: "Consonant + y becomes 'ies'." },
    { question: "What is the plural of 'monkey'?", choices: ["monkies", "monkeys", "monkeyes", "monkies"], correctIndex: 1, explanation: "Vowel + y (e+y), just add 's'." },

    // 31-40: Singular vs Plural Recognition
    { question: "Which word is singular?", choices: ["cats", "dog", "birds", "ants"], correctIndex: 1, explanation: "'Dog' refers to only one animal." },
    { question: "Which word is plural?", choices: ["apple", "banana", "grapes", "melon"], correctIndex: 2, explanation: "'Grapes' ends in s, referring to more than one." },
    { question: "Identify the plural noun.", choices: ["Teacher", "Student", "Schools", "Class"], correctIndex: 2, explanation: "'Schools' is the only plural word here." },
    { question: "Identify the singular noun.", choices: ["Desks", "Chair", "Pencils", "Erasers"], correctIndex: 1, explanation: "'Chair' is singular." },
    { question: "Which is NOT plural?", choices: ["Mice", "Teeth", "Foot", "Geese"], correctIndex: 2, explanation: "'Foot' is singular. The plural is 'feet'." },
    { question: "Which is NOT singular?", choices: ["Man", "Women", "Child", "Tooth"], correctIndex: 1, explanation: "'Women' is plural. The singular is 'woman'." },
    { question: "Choose the plural word.", choices: ["Leaf", "Leaves", "Life", "Loaf"], correctIndex: 1, explanation: "'Leaves' is the plural of 'leaf'." },
    { question: "Choose the singular word.", choices: ["Knives", "Wives", "Life", "Shelves"], correctIndex: 2, explanation: "'Life' is singular." },
    { question: "Is 'Information' singular or plural?", choices: ["Singular (Uncountable)", "Plural", "Both", "Neither"], correctIndex: 0, explanation: "Information is an uncountable noun and is treated as singular." },
    { question: "Is 'Water' singular or plural?", choices: ["Singular (Uncountable)", "Plural", "Both", "Neither"], correctIndex: 0, explanation: "Water is a mass noun, treated as singular." },

    // 41-50: Basic Subject-Verb Agreement
    { question: "The cat ___ sleeping.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Singular subject 'cat' takes singular verb 'is'." },
    { question: "The dogs ___ barking.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Plural subject 'dogs' takes plural verb 'are'." },
    { question: "She ___ a teacher.", choices: ["are", "is", "were", "be"], correctIndex: 1, explanation: "Singular subject 'She' takes 'is'." },
    { question: "They ___ friends.", choices: ["is", "are", "was", "am"], correctIndex: 1, explanation: "Plural subject 'They' takes 'are'." },
    { question: "The book ___ on the table.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Singular subject 'book' takes 'is'." },
    { question: "The pens ___ blue.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Plural subject 'pens' takes 'are'." },
    { question: "My brother ___ tall.", choices: ["are", "is", "were", "have"], correctIndex: 1, explanation: "Singular subject 'brother' takes 'is'." },
    { question: "We ___ happy.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Plural subject 'We' takes 'are'." },
    { question: "He ___ to school.", choices: ["walk", "walks", "walking", "walked"], correctIndex: 1, explanation: "Singular subject 'He' takes the verb with 's' (walks)." },
    { question: "They ___ to school.", choices: ["walk", "walks", "walking", "walked"], correctIndex: 0, explanation: "Plural subject 'They' takes the base verb (walk)." }
  ],

  intermediate: [
    // 1-15: Irregular Plurals
    { question: "What is the plural of 'man'?", choices: ["mans", "mens", "men", "manes"], correctIndex: 2, explanation: "Irregular plural: 'a' changes to 'e'." },
    { question: "What is the plural of 'woman'?", choices: ["womans", "womens", "women", "womanes"], correctIndex: 2, explanation: "Irregular plural: 'woman' becomes 'women'." },
    { question: "What is the plural of 'child'?", choices: ["childs", "children", "childes", "childrens"], correctIndex: 1, explanation: "Child -> Children." },
    { question: "What is the plural of 'foot'?", choices: ["foots", "feet", "feets", "futes"], correctIndex: 1, explanation: "Foot -> Feet." },
    { question: "What is the plural of 'tooth'?", choices: ["tooths", "teeth", "toothes", "teeths"], correctIndex: 1, explanation: "Tooth -> Teeth." },
    { question: "What is the plural of 'goose'?", choices: ["gooses", "geese", "geeses", "gouse"], correctIndex: 1, explanation: "Goose -> Geese." },
    { question: "What is the plural of 'mouse'?", choices: ["mouses", "mice", "mices", "meese"], correctIndex: 1, explanation: "Mouse -> Mice." },
    { question: "What is the plural of 'ox'?", choices: ["oxes", "oxen", "oxs", "oxens"], correctIndex: 1, explanation: "Ox -> Oxen." },
    { question: "What is the plural of 'louse'?", choices: ["louses", "lice", "licses", "louse"], correctIndex: 1, explanation: "Louse -> Lice." },
    { question: "What is the plural of 'person'?", choices: ["persons", "people", "peoples", "persones"], correctIndex: 1, explanation: "'People' is the most common plural, though 'persons' exists in formal contexts." },
    { question: "What is the plural of 'leaf'?", choices: ["leafs", "leaves", "leafes", "leave"], correctIndex: 1, explanation: "Nouns ending in 'f' often change to 'ves'." },
    { question: "What is the plural of 'wolf'?", choices: ["wolfs", "wolves", "wolfes", "wolv"], correctIndex: 1, explanation: "Wolf -> Wolves." },
    { question: "What is the plural of 'knife'?", choices: ["knifes", "knives", "knive", "knifves"], correctIndex: 1, explanation: "Knife -> Knives." },
    { question: "What is the plural of 'wife'?", choices: ["wifes", "wives", "wivies", "wifs"], correctIndex: 1, explanation: "Wife -> Wives." },
    { question: "What is the plural of 'thief'?", choices: ["thiefs", "thieves", "thiefes", "thievs"], correctIndex: 1, explanation: "Thief -> Thieves." },

    // 16-30: Nouns that stay the same (Zero Plural)
    { question: "What is the plural of 'sheep'?", choices: ["sheeps", "sheep", "sheppes", "shoop"], correctIndex: 1, explanation: "Sheep stays the same." },
    { question: "What is the plural of 'deer'?", choices: ["deers", "deer", "deeres", "doer"], correctIndex: 1, explanation: "Deer stays the same." },
    { question: "What is the plural of 'fish' (general)?", choices: ["fishs", "fishes", "fish", "fishies"], correctIndex: 2, explanation: "Fish usually stays the same (Fishes is used for different species)." },
    { question: "What is the plural of 'salmon'?", choices: ["salmons", "salmon", "salmones", "salmen"], correctIndex: 1, explanation: "Salmon stays the same." },
    { question: "What is the plural of 'tuna'?", choices: ["tunas", "tuna", "tunae", "tunes"], correctIndex: 1, explanation: "Tuna usually stays the same in context of food/fishing." },
    { question: "What is the plural of 'moose'?", choices: ["mooses", "meese", "moose", "moos"], correctIndex: 2, explanation: "Moose stays the same." },
    { question: "What is the plural of 'aircraft'?", choices: ["aircrafts", "aircraft", "aircraftes", "air-crafts"], correctIndex: 1, explanation: "Aircraft stays the same." },
    { question: "What is the plural of 'series'?", choices: ["serieses", "series", "serie", "seri"], correctIndex: 1, explanation: "Series is the same in singular and plural." },
    { question: "What is the plural of 'species'?", choices: ["specieses", "specie", "species", "speci"], correctIndex: 2, explanation: "Species is the same in singular and plural." },
    { question: "What is the plural of 'shrimp'?", choices: ["shrimps", "shrimp", "shrimpes", "shramps"], correctIndex: 1, explanation: "Shrimp is often used as a zero plural." },
    { question: "Which is correct?", choices: ["Two sheeps", "Two sheep", "Two sheepses", "Two ship"], correctIndex: 1, explanation: "Sheep never takes an 's'." },
    { question: "Which is correct?", choices: ["Many deers", "Many deer", "Many doer", "Much deer"], correctIndex: 1, explanation: "Deer never takes an 's'." },
    { question: "Which is correct?", choices: ["A herd of mooses", "A herd of moose", "A herd of meese", "A herd of moos"], correctIndex: 1, explanation: "Moose is always moose." },
    { question: "Is 'Music' countable or uncountable?", choices: ["Countable", "Uncountable", "Both", "Neither"], correctIndex: 1, explanation: "Music is uncountable." },
    { question: "Is 'Furniture' countable or uncountable?", choices: ["Countable", "Uncountable", "Both", "Neither"], correctIndex: 1, explanation: "Furniture is uncountable." },

    // 31-40: Compound Nouns Pluralization
    { question: "What is the plural of 'mother-in-law'?", choices: ["mother-in-laws", "mothers-in-law", "mothers-in-laws", "mother-in-law"], correctIndex: 1, explanation: "Pluralize the main person (mother), not the law." },
    { question: "What is the plural of 'passer-by'?", choices: ["passer-bys", "passers-by", "passers-bys", "passer-by"], correctIndex: 1, explanation: "Pluralize the person (passer)." },
    { question: "What is the plural of 'editor-in-chief'?", choices: ["editors-in-chief", "editor-in-chiefs", "editors-in-chiefs", "editor-in-chieves"], correctIndex: 0, explanation: "Pluralize the main word (editor)." },
    { question: "What is the plural of 'runner-up'?", choices: ["runner-ups", "runners-up", "runners-ups", "runner-up"], correctIndex: 1, explanation: "Pluralize the person (runner)." },
    { question: "What is the plural of 'cupful'?", choices: ["cupsful", "cupfuls", "cupsfuls", "cup-fuls"], correctIndex: 1, explanation: "For measurements ending in -ful, add 's' at the end." },
    { question: "What is the plural of 'spoonful'?", choices: ["spoonsful", "spoonfuls", "spoonsfuls", "spoon-fuls"], correctIndex: 1, explanation: "Add 's' to the end: Spoonfuls." },
    { question: "What is the plural of 'toothbrush'?", choices: ["teethbrush", "toothbrushes", "teethbrushes", "toothbrushs"], correctIndex: 1, explanation: "Pluralize the end of the compound word." },
    { question: "What is the plural of 'fireman'?", choices: ["firemans", "firemen", "firesman", "firemens"], correctIndex: 1, explanation: "Man changes to Men." },
    { question: "What is the plural of 'bookshelf'?", choices: ["bookshelfs", "bookshelves", "booksshelf", "bookshelvs"], correctIndex: 1, explanation: "Shelf changes to Shelves." },
    { question: "What is the plural of 'stepchild'?", choices: ["stepchilds", "stepchildren", "stepschild", "stepchildes"], correctIndex: 1, explanation: "Child changes to Children." },

    // 41-50: Nouns ending in 'o'
    { question: "What is the plural of 'potato'?", choices: ["potatos", "potatoes", "potatoies", "potatose"], correctIndex: 1, explanation: "Add '-es' to potato." },
    { question: "What is the plural of 'tomato'?", choices: ["tomatos", "tomatoes", "tomatoies", "tomatose"], correctIndex: 1, explanation: "Add '-es' to tomato." },
    { question: "What is the plural of 'hero'?", choices: ["heros", "heroes", "heroies", "herose"], correctIndex: 1, explanation: "Add '-es' to hero." },
    { question: "What is the plural of 'echo'?", choices: ["echos", "echoes", "echoies", "echose"], correctIndex: 1, explanation: "Add '-es' to echo." },
    { question: "What is the plural of 'radio'?", choices: ["radios", "radioes", "radioies", "radiose"], correctIndex: 0, explanation: "For musical/tech terms ending in 'o', usually just add 's'." },
    { question: "What is the plural of 'piano'?", choices: ["pianos", "pianoes", "pianoies", "pianose"], correctIndex: 0, explanation: "Just add 's' to piano." },
    { question: "What is the plural of 'photo'?", choices: ["photos", "photoes", "photoies", "photose"], correctIndex: 0, explanation: "Just add 's' to photo." },
    { question: "What is the plural of 'video'?", choices: ["videos", "videoes", "videoies", "videose"], correctIndex: 0, explanation: "Just add 's' to video." },
    { question: "What is the plural of 'zoo'?", choices: ["zoos", "zooes", "zooies", "zoose"], correctIndex: 0, explanation: "Just add 's' to zoo." },
    { question: "What is the plural of 'volcano'?", choices: ["volcanos", "volcanoes", "Both A and B", "volcani"], correctIndex: 2, explanation: "Both 'volcanos' and 'volcanoes' are accepted." }
  ],

  advanced: [
    // 1-15: Foreign Plurals (Latin/Greek)
    { question: "What is the plural of 'datum'?", choices: ["datums", "data", "datas", "date"], correctIndex: 1, explanation: "Data is the Latin plural of datum." },
    { question: "What is the plural of 'criterion'?", choices: ["criterions", "criteria", "criterias", "criterion"], correctIndex: 1, explanation: "Criteria is the Greek plural of criterion." },
    { question: "What is the plural of 'phenomenon'?", choices: ["phenomenons", "phenomena", "phenomenas", "phenomeni"], correctIndex: 1, explanation: "Phenomena is the Greek plural." },
    { question: "What is the plural of 'analysis'?", choices: ["analyses", "analysises", "analysis", "analysi"], correctIndex: 0, explanation: "Change 'is' to 'es': Analyses." },
    { question: "What is the plural of 'thesis'?", choices: ["thesises", "theses", "thesis", "thesi"], correctIndex: 1, explanation: "Change 'is' to 'es': Theses." },
    { question: "What is the plural of 'crisis'?", choices: ["crisises", "crises", "crisi", "cries"], correctIndex: 1, explanation: "Change 'is' to 'es': Crises." },
    { question: "What is the plural of 'cactus'?", choices: ["cactuses", "cacti", "Both A and B", "cactus"], correctIndex: 2, explanation: "Both Cacti (Latin) and Cactuses (English) are accepted." },
    { question: "What is the plural of 'fungus'?", choices: ["funguses", "fungi", "Both A and B", "fungu"], correctIndex: 2, explanation: "Both Fungi and Funguses are accepted." },
    { question: "What is the plural of 'nucleus'?", choices: ["nucleuses", "nuclei", "nucleis", "nuclear"], correctIndex: 1, explanation: "Nucleus -> Nuclei." },
    { question: "What is the plural of 'stimulus'?", choices: ["stimuluses", "stimuli", "stimulis", "stimul"], correctIndex: 1, explanation: "Stimulus -> Stimuli." },
    { question: "What is the plural of 'alumnus' (male)?", choices: ["alumni", "alumnae", "alumnuses", "alumnas"], correctIndex: 0, explanation: "Alumnus -> Alumni." },
    { question: "What is the plural of 'alumna' (female)?", choices: ["alumni", "alumnae", "alumnas", "alumnus"], correctIndex: 1, explanation: "Alumna -> Alumnae." },
    { question: "What is the plural of 'bacterium'?", choices: ["bacteriums", "bacteria", "bacterias", "bacteri"], correctIndex: 1, explanation: "Bacterium -> Bacteria." },
    { question: "What is the plural of 'medium'?", choices: ["mediums", "media", "medias", "medi"], correctIndex: 1, explanation: "Medium -> Media (e.g., Social Media)." },
    { question: "What is the plural of 'index'?", choices: ["indexes", "indices", "Both A and B", "index"], correctIndex: 2, explanation: "Indexes (books) or Indices (math)." },

    // 16-30: Subject-Verb Agreement (Collective Nouns)
    { question: "The team ___ winning the game.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Team acting as one unit -> singular verb 'is'." },
    { question: "The team ___ arguing among themselves.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Team members acting individually -> plural verb 'are'." },
    { question: "The committee ___ reached a decision.", choices: ["has", "have", "are", "were"], correctIndex: 0, explanation: "Acting as a unit -> singular 'has'." },
    { question: "The staff ___ in a meeting.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Staff as a unit -> singular 'is'." },
    { question: "The staff ___ working on their own projects.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Individual actions -> plural 'are'." },
    { question: "The audience ___ clapping.", choices: ["was", "were", "is", "has"], correctIndex: 0, explanation: "Audience as a whole -> singular 'was'." },
    { question: "The family ___ eating dinner.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Family as a unit -> singular 'is'." },
    { question: "The jury ___ given its verdict.", choices: ["has", "have", "are", "were"], correctIndex: 0, explanation: "Unit -> singular 'has'." },
    { question: "The jury ___ divided in their opinions.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Divided/Individual -> plural 'are'." },
    { question: "The crowd ___ shouting.", choices: ["was", "were", "are", "have"], correctIndex: 0, explanation: "Crowd as a unit -> singular 'was'." },
    { question: "A pack of wolves ___ approaching.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Subject is 'pack' (singular) -> 'is'." },
    { question: "A bunch of grapes ___ on the table.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Subject is 'bunch' (singular) -> 'is'." },
    { question: "A herd of cattle ___ grazing.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Subject is 'herd' (singular) -> 'is'." },
    { question: "The police ___ here.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "'Police' is always plural -> 'are'." },
    { question: "Cattle ___ raised on the farm.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "'Cattle' is always plural -> 'are'." },

    // 31-40: Subject-Verb Agreement (Quantifiers & Fractions)
    { question: "Half of the pie ___ eaten.", choices: ["was", "were", "are", "have"], correctIndex: 0, explanation: "Pie is singular/uncountable -> 'was'." },
    { question: "Half of the pies ___ eaten.", choices: ["was", "were", "is", "has"], correctIndex: 1, explanation: "Pies is plural -> 'were'." },
    { question: "Some of the milk ___ spilled.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Milk is uncountable -> 'is'." },
    { question: "Some of the students ___ late.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Students is plural -> 'are'." },
    { question: "All of the cake ___ gone.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Cake is singular here -> 'is'." },
    { question: "All of the cookies ___ gone.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Cookies is plural -> 'are'." },
    { question: "A number of students ___ absent.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "'A number of' takes a PLURAL verb -> 'are'." },
    { question: "The number of students ___ increasing.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "'The number of' takes a SINGULAR verb -> 'is'." },
    { question: "Ten dollars ___ a lot of money.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Money/Time/Distance as a unit -> singular 'is'." },
    { question: "Five years ___ a long time.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Time as a unit -> singular 'is'." },

    // 41-50: Plural-Only Nouns
    { question: "The scissors ___ sharp.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Scissors is plural -> 'are'." },
    { question: "My glasses ___ broken.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Glasses is plural -> 'are'." },
    { question: "His pants ___ torn.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Pants is plural -> 'are'." },
    { question: "The binoculars ___ helpful.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Binoculars is plural -> 'are'." },
    { question: "Her belongings ___ packed.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Belongings is plural -> 'are'." },
    { question: "The goods ___ delivered.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Goods is plural -> 'are'." },
    { question: "My shorts ___ dirty.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Shorts is plural -> 'are'." },
    { question: "The tweezers ___ small.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Tweezers is plural -> 'are'." },
    { question: "The pliers ___ rusty.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Pliers is plural -> 'are'." },
    { question: "Thanks ___ due to him.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Thanks is plural -> 'are'." }
  ],

  super: [
    // 1-15: Tricky Subject-Verb Agreement (Proximity & Indefinite)
    { question: "Either the boy or the girls ___ playing.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Either/Or: Agree with the closest noun (girls) -> 'are'." },
    { question: "Either the girls or the boy ___ playing.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Either/Or: Agree with the closest noun (boy) -> 'is'." },
    { question: "Neither the manager nor the employees ___ present.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Neither/Nor: Agree with closest (employees) -> 'are'." },
    { question: "Neither the employees nor the manager ___ present.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Neither/Nor: Agree with closest (manager) -> 'is'." },
    { question: "Each of the students ___ a book.", choices: ["have", "has", "are", "were"], correctIndex: 1, explanation: "'Each' is singular -> 'has'." },
    { question: "Everyone ___ welcome.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "'Everyone' is singular -> 'is'." },
    { question: "Somebody ___ knocking.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "'Somebody' is singular -> 'is'." },
    { question: "Nobody ___ the answer.", choices: ["know", "knows", "knowing", "known"], correctIndex: 1, explanation: "'Nobody' is singular -> 'knows'." },
    { question: "Many a student ___ tried.", choices: ["have", "has", "are", "were"], correctIndex: 1, explanation: "'Many a' is followed by a singular noun and verb -> 'has'." },
    { question: "Bread and butter ___ my favorite breakfast.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Compound subject forming ONE idea -> singular 'is'." },
    { question: "Gold and silver ___ precious metals.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Two distinct items -> plural 'are'." },
    { question: "The teacher, along with the students, ___ coming.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Ignore phrases like 'along with'. Subject is 'teacher' (singular) -> 'is'." },
    { question: "The students, as well as the teacher, ___ coming.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Ignore 'as well as'. Subject is 'students' (plural) -> 'are'." },
    { question: "One of the boxes ___ open.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "'One' is the subject -> singular 'is'." },
    { question: "The only one of the students who ___ passing is John.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "'The only one' -> singular 'is'." },

    // 16-30: Abstract & Mass Nouns Logic
    { question: "Measles ___ dangerous.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Disease names ending in s -> singular 'is'." },
    { question: "Mumps ___ painful.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Disease names -> singular 'is'." },
    { question: "Physics ___ interesting.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Subjects ending in s -> singular 'is'." },
    { question: "Politics ___ a dirty game.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Activities ending in s -> singular 'is'." },
    { question: "The news ___ shocking.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "News -> singular 'is'." },
    { question: "Furniture ___ expensive.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Furniture is uncountable -> singular 'is'." },
    { question: "Luggage ___ heavy.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Luggage is uncountable -> singular 'is'." },
    { question: "Knowledge ___ power.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Abstract noun -> singular 'is'." },
    { question: "Advice ___ helpful.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Abstract noun -> singular 'is'." },
    { question: "Traffic ___ bad today.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Mass noun -> singular 'is'." },
    { question: "My hair ___ long.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Hair (on head) is uncountable -> singular 'is'." },
    { question: "Two hairs ___ in my soup.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Individual strands -> plural 'are'." },
    { question: "Paper ___ made from wood.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Material -> singular 'is'." },
    { question: "Legal papers ___ signed.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Documents -> plural 'are'." },
    { question: "Iron ___ a metal.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Material -> singular 'is'." },

    // 31-50: Advanced Singular/Plural Nuances
    { question: "The jury ___ given its verdict.", choices: ["has", "have", "are", "were"], correctIndex: 0, explanation: "Unit -> 'has'." },
    { question: "The jury ___ divided.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Individuals -> 'are'." },
    { question: "Fish ___ swimming.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Multiple fish -> 'are'." },
    { question: "There ___ many reasons.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Subject is 'reasons' (after verb) -> 'are'." },
    { question: "There ___ a reason.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Subject is 'reason' -> 'is'." },
    { question: "Here ___ the bus.", choices: ["come", "comes", "coming", "came"], correctIndex: 1, explanation: "Subject 'bus' -> 'comes'." },
    { question: "Here ___ the buses.", choices: ["come", "comes", "coming", "came"], correctIndex: 0, explanation: "Subject 'buses' -> 'come'." },
    { question: "Three miles ___ a long way.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Distance as unit -> 'is'." },
    { question: "Fifty pesos ___ not enough.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Money as unit -> 'is'." },
    { question: "Two hours ___ passed.", choices: ["has", "have", "is", "are"], correctIndex: 0, explanation: "Time as unit -> 'has'." },
    { question: "Statistics (the subject) ___ difficult.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Field of study -> 'is'." },
    { question: "Statistics (the data) ___ misleading.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "Facts/Data -> 'are'." },
    { question: "A pair of shoes ___ stolen.", choices: ["was", "were", "are", "have"], correctIndex: 0, explanation: "Subject is 'pair' -> 'was'." },
    { question: "The shoes ___ stolen.", choices: ["was", "were", "is", "has"], correctIndex: 1, explanation: "Subject is 'shoes' -> 'were'." },
    { question: "My family ___ here.", choices: ["is", "are", "were", "have"], correctIndex: 0, explanation: "Unit -> 'is'." },
    { question: "The rich ___ taxes.", choices: ["pay", "pays", "paying", "paid"], correctIndex: 0, explanation: "'The rich' = Rich people (plural) -> 'pay'." },
    { question: "The poor ___ help.", choices: ["need", "needs", "needing", "needed"], correctIndex: 0, explanation: "'The poor' = Poor people (plural) -> 'need'." },
    { question: "The blind ___ guided.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "'The blind' = Blind people -> 'are'." },
    { question: "The French ___ good food.", choices: ["love", "loves", "loving", "loved"], correctIndex: 0, explanation: "'The French' = French people -> 'love'." },
    { question: "The Chinese ___ diligent.", choices: ["is", "are", "was", "has"], correctIndex: 1, explanation: "'The Chinese' = Chinese people -> 'are'." }
  ]
};
