const GENDER_QUESTIONS = {
  beginner: [
    // 1-10: Identifying Masculine Nouns
    { question: "Which word is a masculine noun?", choices: ["Mother", "Father", "Sister", "Aunt"], correctIndex: 1, explanation: "Correct! 'Father' is a male parent. All the other options (Mother, Sister, Aunt) refer to female relatives." },
    { question: "Select the masculine noun:", choices: ["Queen", "King", "Princess", "Lady"], correctIndex: 1, explanation: "'King' is a male ruler. The female equivalent is Queen." },
    { question: "Which noun refers to a male?", choices: ["Niece", "Uncle", "Daughter", "Grandma"], correctIndex: 1, explanation: "'Uncle' refers to the brother of your parent (male). 'Niece', 'Daughter', and 'Grandma' are all females." },
    { question: "Find the masculine noun:", choices: ["Son", "Daughter", "Wife", "Mother"], correctIndex: 0, explanation: "'Son' is a male child. The feminine equivalent is Daughter." },
    { question: "Which word is masculine?", choices: ["Widow", "Widower", "Bride", "Girl"], correctIndex: 1, explanation: "'Widower' is a man whose wife has died. A woman whose husband has died is called a 'Widow'." },
    { question: "Select the male animal:", choices: ["Hen", "Cow", "Bull", "Duck"], correctIndex: 2, explanation: "'Bull' is the specific term for a male bovine (cattle). Hen, Cow, and Duck (specifically) refer to females." },
    { question: "Which is masculine?", choices: ["Boy", "Girl", "Lady", "Madam"], correctIndex: 0, explanation: "'Boy' is a young male. The other terms refer to females." },
    { question: "Find the masculine noun:", choices: ["Husband", "Wife", "Mother", "Madam"], correctIndex: 0, explanation: "'Husband' is a male spouse. 'Wife' is the female spouse." },
    { question: "Which noun is masculine?", choices: ["Actor", "Actress", "Heroine", "Waitress"], correctIndex: 0, explanation: "'Actor' is the masculine form. While 'Actor' can be used for both genders today, it is historically the male term, whereas the others are strictly feminine." },
    { question: "Select the masculine word:", choices: ["Gentleman", "Lady", "Woman", "Madam"], correctIndex: 0, explanation: "'Gentleman' refers to a polite man. The female equivalent is 'Lady'." },

    // 11-20: Identifying Feminine Nouns
    { question: "Which word is a feminine noun?", choices: ["Brother", "Uncle", "Sister", "Father"], correctIndex: 2, explanation: "'Sister' is a female sibling. Brother, Uncle, and Father are all males." },
    { question: "Select the feminine noun:", choices: ["Rooster", "Hen", "Bull", "Drake"], correctIndex: 1, explanation: "'Hen' is a female chicken. The male is called a Rooster." },
    { question: "Which noun refers to a female?", choices: ["Nephew", "Niece", "Son", "King"], correctIndex: 1, explanation: "'Niece' is the daughter of a sibling (female). The male version is Nephew." },
    { question: "Find the feminine noun:", choices: ["Grandfather", "Grandmother", "Uncle", "Dad"], correctIndex: 1, explanation: "'Grandmother' is a female grandparent. All other options refer to males." },
    { question: "Which word is feminine?", choices: ["Prince", "Princess", "Duke", "Lord"], correctIndex: 1, explanation: "'Princess' is a female royal. The male equivalent is Prince." },
    { question: "Select the female animal:", choices: ["Lion", "Lioness", "Tiger", "Leopard"], correctIndex: 1, explanation: "'Lioness' is the specific term for a female lion. The suffix '-ess' often indicates the feminine form." },
    { question: "Which is feminine?", choices: ["Lad", "Lass", "Boy", "Man"], correctIndex: 1, explanation: "'Lass' is a Scottish/English term for a girl or young woman. 'Lad' is the male version." },
    { question: "Find the feminine noun:", choices: ["Landlord", "Landlady", "Man", "Sir"], correctIndex: 1, explanation: "'Landlady' is a woman who owns and rents out property. The male is 'Landlord'." },
    { question: "Which noun is feminine?", choices: ["Hero", "Heroine", "Actor", "Waiter"], correctIndex: 1, explanation: "'Heroine' is a female hero. Hero, Actor, and Waiter are traditionally masculine." },
    { question: "Select the feminine word:", choices: ["Monk", "Nun", "Priest", "Friar"], correctIndex: 1, explanation: "'Nun' is a female member of a religious order. Monk, Priest, and Friar are titles for men." },

    // 21-30: Identifying Neuter Nouns (Objects)
    { question: "Which noun is neuter gender?", choices: ["Baby", "Table", "Mother", "Rooster"], correctIndex: 1, explanation: "'Table' is a non-living object, so it has no gender (Neuter). Animals and humans usually have gender." },
    { question: "Select the neuter noun:", choices: ["Computer", "Teacher", "Doctor", "Nurse"], correctIndex: 0, explanation: "'Computer' is a machine (Neuter). Teacher, Doctor, and Nurse are people (Common Gender)." },
    { question: "Which word is neuter?", choices: ["Boy", "School", "Girl", "Man"], correctIndex: 1, explanation: "'School' is a place or building, making it neuter. Boy, Girl, and Man are gendered people." },
    { question: "Find the neuter noun:", choices: ["Tree", "Cat", "Dog", "Horse"], correctIndex: 0, explanation: "Plants like a 'Tree' are considered neuter because they are treated as objects in English grammar." },
    { question: "Which is neuter?", choices: ["Phone", "Father", "Aunt", "Son"], correctIndex: 0, explanation: "'Phone' is an inanimate object. The others are male or female relatives." },
    { question: "Select the neuter noun:", choices: ["Ball", "Player", "Coach", "Referee"], correctIndex: 0, explanation: "'Ball' is an object. Player, Coach, and Referee are people (Common Gender)." },
    { question: "Which word refers to a thing?", choices: ["Chair", "Student", "Principal", "Janitor"], correctIndex: 0, explanation: "'Chair' is a thing (Neuter). The others are roles held by people." },
    { question: "Find the neuter noun:", choices: ["River", "Swimmer", "Fish", "Crab"], correctIndex: 0, explanation: "'River' is a geographical feature (Neuter). Living creatures like Swimmers or Fish have gender (even if we don't know it)." },
    { question: "Which noun has no gender?", choices: ["Book", "Author", "Writer", "Poet"], correctIndex: 0, explanation: "'Book' is an object. Authors, Writers, and Poets are people." },
    { question: "Select the neuter noun:", choices: ["Car", "Driver", "Mechanic", "Passenger"], correctIndex: 0, explanation: "'Car' is a vehicle (Neuter). The Driver, Mechanic, and Passenger are people." },

    // 31-40: Identifying Common Nouns (Either Male or Female)
    { question: "Which noun is common gender?", choices: ["King", "Queen", "Teacher", "Boy"], correctIndex: 2, explanation: "A 'Teacher' can be either a man or a woman, so it is Common Gender. King is masculine; Queen is feminine." },
    { question: "Select the common noun:", choices: ["Mother", "Parent", "Father", "Sister"], correctIndex: 1, explanation: "'Parent' is the general term that covers both Mother and Father." },
    { question: "Which word implies either gender?", choices: ["Doctor", "Actress", "Nun", "Monk"], correctIndex: 0, explanation: "A 'Doctor' can be male or female. Actress, Nun, and Monk have specific genders." },
    { question: "Find the common gender noun:", choices: ["Friend", "Boyfriend", "Girlfriend", "Husband"], correctIndex: 0, explanation: "'Friend' is gender-neutral. Boyfriend and Husband are male; Girlfriend is female." },
    { question: "Which is common gender?", choices: ["Baby", "Boy", "Man", "Woman"], correctIndex: 0, explanation: "A 'Baby' can be a boy or a girl, so it is considered common gender until the sex is specified." },
    { question: "Select the common noun:", choices: ["Student", "Headmaster", "Headmistress", "King"], correctIndex: 0, explanation: "'Student' applies to anyone studying, regardless of gender. Headmaster is male; Headmistress is female." },
    { question: "Which word is common gender?", choices: ["Cousin", "Uncle", "Aunt", "Niece"], correctIndex: 0, explanation: "'Cousin' refers to the child of an aunt/uncle and can be male or female." },
    { question: "Find the common gender noun:", choices: ["Guest", "Hostess", "Landlady", "Waiter"], correctIndex: 0, explanation: "'Guest' applies to any visitor. Hostess and Landlady are female; Waiter is male." },
    { question: "Which is common gender?", choices: ["Neighbor", "Man", "Gentleman", "Lady"], correctIndex: 0, explanation: "Your 'Neighbor' could be a man or a woman." },
    { question: "Select the common noun:", choices: ["Enemy", "King", "Prince", "Duke"], correctIndex: 0, explanation: "An 'Enemy' can be of any gender. King, Prince, and Duke are strictly male titles." },

    // 41-50: Basic Matching
    { question: "What is the feminine of 'Boy'?", choices: ["Girl", "Woman", "Lady", "Aunt"], correctIndex: 0, explanation: "The opposite of Boy is Girl." },
    { question: "What is the masculine of 'Mother'?", choices: ["Father", "Uncle", "Grandpa", "Brother"], correctIndex: 0, explanation: "The partner of Mother is Father." },
    { question: "What is the feminine of 'Husband'?", choices: ["Wife", "Spouse", "Partner", "Girl"], correctIndex: 0, explanation: "The female partner of a Husband is a Wife." },
    { question: "What is the masculine of 'Sister'?", choices: ["Brother", "Cousin", "Father", "Uncle"], correctIndex: 0, explanation: "The male sibling is a Brother; the female is a Sister." },
    { question: "What is the feminine of 'King'?", choices: ["Queen", "Princess", "Duchess", "Lady"], correctIndex: 0, explanation: "King rules with a Queen." },
    { question: "What is the masculine of 'Aunt'?", choices: ["Uncle", "Father", "Nephew", "Brother"], correctIndex: 0, explanation: "Aunt corresponds to Uncle." },
    { question: "What is the feminine of 'Son'?", choices: ["Daughter", "Niece", "Sister", "Mother"], correctIndex: 0, explanation: "Son is male offspring; Daughter is female offspring." },
    { question: "What is the masculine of 'Grandmother'?", choices: ["Grandfather", "Father", "Uncle", "Brother"], correctIndex: 0, explanation: "Grandmother pairs with Grandfather." },
    { question: "What is the feminine of 'Man'?", choices: ["Woman", "Girl", "Lady", "Person"], correctIndex: 0, explanation: "Man pairs with Woman." },
    { question: "What is the masculine of 'Madam'?", choices: ["Sir", "Mister", "Boy", "Man"], correctIndex: 0, explanation: "Madam is a polite title for women; Sir is the polite title for men." }
  ],

  intermediate: [
    // 1-10: Animal Genders
    { question: "What is the feminine of 'Bull'?", choices: ["Cow", "Heifer", "Mare", "Sow"], correctIndex: 0, explanation: "Correct. A 'Bull' is a male bovine, and a 'Cow' is the female." },
    { question: "What is the masculine of 'Hen'?", choices: ["Rooster", "Drake", "Gander", "Ram"], correctIndex: 0, explanation: "A 'Hen' is a female chicken. The male chicken is called a 'Rooster'." },
    { question: "What is the feminine of 'Horse' (specifically a stallion)?", choices: ["Mare", "Ewe", "Vixen", "Doe"], correctIndex: 0, explanation: "For horses, the male is a Stallion and the female is a 'Mare'." },
    { question: "What is the masculine of 'Duck'?", choices: ["Drake", "Goose", "Gander", "Swan"], correctIndex: 0, explanation: "Strictly speaking, 'Duck' is female. The male is called a 'Drake'." },
    { question: "What is the feminine of 'Fox'?", choices: ["Vixen", "Sow", "Ewe", "Doe"], correctIndex: 0, explanation: "A male fox is a Dog or Tod; the female fox is called a 'Vixen'." },
    { question: "What is the masculine of 'Goose'?", choices: ["Gander", "Drake", "Rooster", "Bull"], correctIndex: 0, explanation: "Goose is actually the female term (or the general term). The male is specifically called a 'Gander'." },
    { question: "What is the feminine of 'Ram' (Sheep)?", choices: ["Ewe", "Sow", "Doe", "Mare"], correctIndex: 0, explanation: "A 'Ram' is a male sheep. The female sheep is called an 'Ewe' (pronounced like 'you')." },
    { question: "What is the masculine of 'Sow' (Pig)?", choices: ["Boar", "Bull", "Ram", "Drake"], correctIndex: 0, explanation: "A 'Sow' is a female pig. The male pig is called a 'Boar'." },
    { question: "What is the feminine of 'Tiger'?", choices: ["Tigress", "Tigeress", "Tigra", "Tigris"], correctIndex: 0, explanation: "We add the suffix '-ess' to make it feminine: 'Tigress'." },
    { question: "What is the masculine of 'Lioness'?", choices: ["Lion", "Tiger", "Leopard", "Cat"], correctIndex: 0, explanation: "Lioness is female; 'Lion' is the male (and general) term." },

    // 11-20: Human Roles & Titles (Set 1)
    { question: "What is the feminine of 'Bachelor'?", choices: ["Spinster", "Wife", "Widow", "Lady"], correctIndex: 0, explanation: "A 'Bachelor' is an unmarried man. The historical term for an unmarried woman is 'Spinster' (though 'Bachelorette' is common in modern pop culture)." },
    { question: "What is the masculine of 'Witch'?", choices: ["Wizard", "Warlock", "Sorcerer", "Magician"], correctIndex: 0, explanation: "In folklore, a female magic-user is a Witch, and the male equivalent is a 'Wizard'." },
    { question: "What is the feminine of 'Monk'?", choices: ["Nun", "Priestess", "Sister", "Lady"], correctIndex: 0, explanation: "A Monk lives in a monastery (male); a 'Nun' lives in a convent (female)." },
    { question: "What is the masculine of 'Bride'?", choices: ["Bridegroom", "Groom", "Husband", "Bachelor"], correctIndex: 0, explanation: "The woman getting married is the Bride; the man is the 'Bridegroom' (or simply Groom)." },
    { question: "What is the feminine of 'Count'?", choices: ["Countess", "Princess", "Duchess", "Baroness"], correctIndex: 0, explanation: "We add '-ess' to Count to get 'Countess'. Princess goes with Prince, Duchess with Duke." },
    { question: "What is the masculine of 'Hostess'?", choices: ["Host", "Waiter", "Steward", "Manager"], correctIndex: 0, explanation: "Hostess is female; 'Host' is male." },
    { question: "What is the feminine of 'God'?", choices: ["Goddess", "Angel", "Saint", "Spirit"], correctIndex: 0, explanation: "The female deity is a 'Goddess'." },
    { question: "What is the masculine of 'Empress'?", choices: ["Emperor", "King", "Tsar", "Sultan"], correctIndex: 0, explanation: "Empress is the female ruler; 'Emperor' is the male ruler." },
    { question: "What is the feminine of 'Master'?", choices: ["Mistress", "Miss", "Mrs", "Lady"], correctIndex: 0, explanation: "Historically, Master (male) pairs with 'Mistress' (female)." },
    { question: "What is the masculine of 'Widow'?", choices: ["Widower", "Bachelor", "Single", "Husband"], correctIndex: 0, explanation: "This is a special case! Usually, we add a suffix to the male word. Here, we add '-er' to the female word 'Widow' to get the male 'Widower'." },

    // 21-30: Human Roles & Titles (Set 2)
    { question: "What is the feminine of 'Waiter'?", choices: ["Waitress", "Server", "Stewardess", "Maid"], correctIndex: 0, explanation: "Waiter (Male) becomes 'Waitress' (Female), although 'Server' is a popular neutral term now." },
    { question: "What is the masculine of 'Stewardess'?", choices: ["Steward", "Pilot", "Waiter", "Host"], correctIndex: 0, explanation: "Stewardess is the female term; 'Steward' is the male term." },
    { question: "What is the feminine of 'Duke'?", choices: ["Duchess", "Countess", "Princess", "Lady"], correctIndex: 0, explanation: "A Duke's wife or a female ruler of a duchy is a 'Duchess'." },
    { question: "What is the masculine of 'Lady'?", choices: ["Lord", "Gentleman", "Sir", "Knight"], correctIndex: 0, explanation: "In nobility, 'Lady' pairs with 'Lord'. In general politeness, 'Lady' pairs with 'Gentleman'." },
    { question: "What is the feminine of 'Nephew'?", choices: ["Niece", "Cousin", "Sister", "Aunt"], correctIndex: 0, explanation: "Your brother's or sister's son is your Nephew; their daughter is your 'Niece'." },
    { question: "What is the masculine of 'Landlady'?", choices: ["Landlord", "Owner", "Master", "Host"], correctIndex: 0, explanation: "The male owner of a rental property is the 'Landlord'." },
    { question: "What is the feminine of 'Headmaster'?", choices: ["Headmistress", "Principal", "Teacher", "Lady"], correctIndex: 0, explanation: "The male principal is a Headmaster; the female is a 'Headmistress'." },
    { question: "What is the masculine of 'Policewoman'?", choices: ["Policeman", "Police officer", "Cop", "Sergeant"], correctIndex: 0, explanation: "Policewoman corresponds to 'Policeman'. 'Police Officer' is the gender-neutral term." },
    { question: "What is the feminine of 'Salesman'?", choices: ["Saleswoman", "Saleslady", "Both A and B", "Seller"], correctIndex: 2, explanation: "Both terms are used. 'Saleswoman' is more formal and professional, while 'Saleslady' is a bit more traditional." },
    { question: "What is the masculine of 'Spokeswoman'?", choices: ["Spokesman", "Speaker", "Talker", "Reporter"], correctIndex: 0, explanation: "Spokeswoman pairs with 'Spokesman'." },

    // 31-40: Pronoun Agreement (Basic)
    { question: "The boy lost ___ ball.", choices: ["his", "her", "its", "their"], correctIndex: 0, explanation: "The subject 'boy' is masculine, so we use the masculine possessive pronoun 'his'." },
    { question: "The girl finished ___ homework.", choices: ["her", "his", "its", "their"], correctIndex: 0, explanation: "The subject 'girl' is feminine, so we use 'her'." },
    { question: "The dog wagged ___ tail.", choices: ["its", "his", "her", "their"], correctIndex: 0, explanation: "For animals where the gender is not personal or specified, we generally use the neuter 'its'." },
    { question: "The teacher asked the student to bring ___ book.", choices: ["his or her", "its", "it", "she"], correctIndex: 0, explanation: "'Student' is common gender (can be male or female). 'His or her' covers both possibilities correctly." },
    { question: "My mother loves ___ garden.", choices: ["her", "his", "its", "their"], correctIndex: 0, explanation: "Mother is feminine, so we must use 'her'." },
    { question: "The king wore ___ crown.", choices: ["his", "her", "its", "their"], correctIndex: 0, explanation: "King is masculine, so we use 'his'." },
    { question: "The car has lost ___ shine.", choices: ["its", "his", "her", "their"], correctIndex: 0, explanation: "A 'car' is a neuter object, so we use 'its'." },
    { question: "The baby is crying for ___ mother.", choices: ["its", "his", "her", "their"], correctIndex: 0, explanation: "When the sex of a baby is not specified or emphasized, English allows the use of 'its'." },
    { question: "Every girl must clean ___ room.", choices: ["her", "his", "its", "their"], correctIndex: 0, explanation: "The subject 'Every girl' is technically singular and feminine, so 'her' is the grammatically correct choice." },
    { question: "Every boy must bring ___ lunch.", choices: ["his", "her", "its", "their"], correctIndex: 0, explanation: "The subject 'Every boy' is singular and masculine, so we use 'his'." },

    // 41-50: Contextual Identification
    { question: "Which word is masculine? 'The mare and the stallion ran.'", choices: ["mare", "stallion", "ran", "the"], correctIndex: 1, explanation: "A 'Stallion' is a male horse. A 'Mare' is a female horse." },
    { question: "Which word is feminine? 'The ewe and the ram grazed.'", choices: ["ewe", "ram", "grazed", "the"], correctIndex: 0, explanation: "An 'Ewe' (pronounced 'you') is a female sheep. The 'Ram' is the male." },
    { question: "Identify the neuter noun: 'He put the computer on the desk.'", choices: ["He", "computer", "desk", "Both B and C"], correctIndex: 3, explanation: "Correct! Both 'computer' and 'desk' are inanimate objects, making them neuter gender." },
    { question: "Identify the common noun: 'The doctor called the nurse.'", choices: ["doctor", "nurse", "Both A and B", "called"], correctIndex: 2, explanation: "Historically, nurses were female and doctors male, but linguistically, BOTH 'Doctor' and 'Nurse' are common nouns—they can apply to any gender." },
    { question: "In 'The ship struck an iceberg', ships are sometimes poetically referred to as:", choices: ["he", "she", "it", "they"], correctIndex: 1, explanation: "By tradition, sailors and writers often personify ships as women, referring to them as 'she'." },
    { question: "Which is the gender-neutral term for 'Fireman'?", choices: ["Firefighter", "Firewoman", "Fire person", "Burner"], correctIndex: 0, explanation: "'Firefighter' focuses on the job, not the gender, making it the preferred modern term." },
    { question: "Which is the gender-neutral term for 'Policeman'?", choices: ["Police officer", "Cop", "Guard", "Detective"], correctIndex: 0, explanation: "'Police officer' is the professional, formal, and gender-neutral title." },
    { question: "Which is the gender-neutral term for 'Mailman'?", choices: ["Mail carrier", "Post person", "Letter bringer", "Mail boy"], correctIndex: 0, explanation: "'Mail carrier' or 'Postal worker' are standard neutral terms." },
    { question: "Which is the gender-neutral term for 'Stewardess'?", choices: ["Flight attendant", "Plane server", "Air host", "Flyer"], correctIndex: 0, explanation: "'Flight attendant' is the correct modern term for the crew who assist passengers." },
    { question: "Which is the gender-neutral term for 'Chairman'?", choices: ["Chairperson", "Chair", "Both A and B", "Chairlady"], correctIndex: 2, explanation: "Both 'Chairperson' and 'The Chair' are widely accepted as neutral replacements." }
  ],

  advanced: [
    // 1-10: Gender-Neutral Language (Singular 'They')
    { question: "The student lost ____ book. (Gender unknown)", choices: ["his", "her", "their", "its"], correctIndex: 2, explanation: "When we don't know the gender of a person (like 'student'), the singular 'their' is the standard, inclusive choice in modern English." },
    { question: "If anyone calls, tell ____ I am busy.", choices: ["him", "her", "them", "it"], correctIndex: 2, explanation: "'Anyone' implies a person of unknown gender. We use 'them' (or him/her) as the pronoun reference, but 'them' is the safest neutral option." },
    { question: "Every passenger must hold ____ ticket.", choices: ["his", "her", "their", "its"], correctIndex: 2, explanation: "Using 'their' avoids assuming that 'passenger' refers only to men or only to women." },
    { question: "Somebody left ____ umbrella here.", choices: ["his", "her", "their", "its"], correctIndex: 2, explanation: "'Somebody' is indefinite. Using 'their' covers all possibilities." },
    { question: "A good leader listens to ____ team.", choices: ["his", "her", "their", "its"], correctIndex: 2, explanation: "Leaders can be any gender, so 'their' is the most appropriate choice." },
    { question: "Each candidate must submit ____ resume.", choices: ["his", "his or her", "their", "All of the above"], correctIndex: 3, explanation: "Grammatically, 'his' is traditional (generic masculine), 'his or her' is precise, and 'their' is the modern standard. All are defensible depending on the style guide." },
    { question: "Who dropped ____ wallet?", choices: ["his", "her", "their", "its"], correctIndex: 2, explanation: "Since we are asking 'Who', we do not know the gender. 'Their' fits best." },
    { question: "No one should lose ____ hope.", choices: ["his", "her", "their", "its"], correctIndex: 2, explanation: "Similar to 'everyone' or 'anyone', 'No one' is treated as a gender-neutral singular antecedent, taking 'their'." },
    { question: "The parent brought ____ child to school.", choices: ["his", "her", "their", "its"], correctIndex: 2, explanation: "'Parent' is common gender. Using 'his' or 'her' alone might exclude fathers or mothers." },
    { question: "Usually, a doctor cares for ____ patients.", choices: ["his", "her", "their", "its"], correctIndex: 2, explanation: "Using 'their' helps avoid the stereotype that all doctors are men." },

    // 11-20: Modern Usage vs. Traditional (Shift to Neutral)
    { question: "Which term is now preferred over 'Stewardess'?", choices: ["Flight attendant", "Air lady", "Plane host", "Steward"], correctIndex: 0, explanation: "'Flight attendant' describes the role without specifying gender, making it the preferred professional title." },
    { question: "Instead of 'Policeman', we should use:", choices: ["Cop", "Police officer", "Patrolman", "Guard"], correctIndex: 1, explanation: "'Police officer' is formal and inclusive." },
    { question: "Instead of 'Mailman', we use:", choices: ["Mail carrier", "Postman", "Mail boy", "Letter man"], correctIndex: 0, explanation: "'Mail carrier' is the gender-neutral standard." },
    { question: "Instead of 'Fireman', we use:", choices: ["Firefighter", "Fire person", "Burner", "Rescuer"], correctIndex: 0, explanation: "'Firefighter' is the correct term." },
    { question: "The term 'Actor' is now often used for:", choices: ["Males only", "Females only", "Both males and females", "Neither"], correctIndex: 2, explanation: "While 'Actress' exists, many female performers prefer 'Actor' as a professional title equal to their male counterparts." },
    { question: "Which is the gender-neutral form of 'Mankind'?", choices: ["Humankind", "Man", "Humanity", "Both A and C"], correctIndex: 3, explanation: "Both 'Humankind' and 'Humanity' refer to all people without using the gendered word 'man'." },
    { question: "Instead of 'Man-made', use:", choices: ["Synthetic", "Artificial", "Manufactured", "All of the above"], correctIndex: 3, explanation: "All of these words (Synthetic, Artificial, Manufactured) describe things made by humans without using gendered language." },
    { question: "Instead of 'Chairman', use:", choices: ["Chairperson", "Chair", "Head", "All of the above"], correctIndex: 3, explanation: "All options are valid ways to avoid the assumption that the leader is a man." },
    { question: "Instead of 'Forefathers', use:", choices: ["Ancestors", "Dads", "Old men", "History"], correctIndex: 0, explanation: "'Ancestors' includes both the men and women who came before us." },
    { question: "Instead of 'Businessman', use:", choices: ["Business person", "Executive", "Business professional", "All of the above"], correctIndex: 3, explanation: "These terms focus on the profession rather than the gender." },

    // 21-30: Personification (Poetic Gender)
    { question: "In poetry, the 'Sun' is often personified as:", choices: ["Masculine", "Feminine", "Neuter", "Common"], correctIndex: 0, explanation: "Because of its strength and power, the Sun is traditionally personified as Masculine (He)." },
    { question: "In poetry, the 'Moon' is often personified as:", choices: ["Masculine", "Feminine", "Neuter", "Common"], correctIndex: 1, explanation: "Because of its association with beauty and gentleness, the Moon is traditionally personified as Feminine (She)." },
    { question: "In poetry, 'Nature' is often personified as:", choices: ["Masculine", "Feminine", "Neuter", "Common"], correctIndex: 1, explanation: "We often hear the phrase 'Mother Nature', indicating a Feminine personification." },
    { question: "In poetry, 'Death' is often personified as:", choices: ["Masculine", "Feminine", "Neuter", "Common"], correctIndex: 0, explanation: "Death (e.g., The Grim Reaper) is typically depicted as a male figure (Masculine)." },
    { question: "In poetry, 'Earth' is often personified as:", choices: ["Masculine", "Feminine", "Neuter", "Common"], correctIndex: 1, explanation: "We refer to the planet as 'Mother Earth', so it is Feminine." },
    { question: "In poetry, 'War' is often personified as:", choices: ["Masculine", "Feminine", "Neuter", "Common"], correctIndex: 0, explanation: "War is associated with aggression and violence, qualities traditionally linked to Masculine personification in literature." },
    { question: "In poetry, 'Spring' is often personified as:", choices: ["Masculine", "Feminine", "Neuter", "Common"], correctIndex: 1, explanation: "Spring is associated with birth, fertility, and new life, which are Feminine qualities." },
    { question: "In poetry, 'Time' is often personified as:", choices: ["Masculine", "Feminine", "Neuter", "Common"], correctIndex: 0, explanation: "We use the phrase 'Father Time', so it is Masculine." },
    { question: "Ships and boats are traditionally referred to as:", choices: ["He", "She", "It", "They"], correctIndex: 1, explanation: "Tradition among sailors dictates that a ship is a 'She' to be protected and loved." },
    { question: "Countries, when referred to with affection, are often:", choices: ["Masculine", "Feminine", "Neuter", "Common"], correctIndex: 1, explanation: "Countries are often personified as mothers (e.g., 'Motherland'), making them Feminine." },

    // 31-40: Specific Animal Terms (Advanced)
    { question: "What is the feminine of 'Boar'?", choices: ["Sow", "Doe", "Mare", "Hen"], correctIndex: 0, explanation: "A 'Boar' is a male pig; the female is a 'Sow'." },
    { question: "What is the masculine of 'Doe'?", choices: ["Buck", "Bull", "Ram", "Stallion"], correctIndex: 0, explanation: "A 'Doe' is a female deer (or rabbit). The male is a 'Buck'." },
    { question: "What is the masculine of 'Ewe'?", choices: ["Ram", "Buck", "Boar", "Bull"], correctIndex: 0, explanation: "An 'Ewe' is a female sheep. The male is a 'Ram'." },
    { question: "What is the feminine of 'Colt'?", choices: ["Filly", "Mare", "Foal", "Doe"], correctIndex: 0, explanation: "A 'Colt' is a young male horse. A 'Filly' is a young female horse." },
    { question: "What is the masculine of 'Filly'?", choices: ["Colt", "Foal", "Stallion", "Gelding"], correctIndex: 0, explanation: "A 'Filly' is a young female horse. The young male equivalent is 'Colt'." },
    { question: "What is the gender-neutral term for 'Ram/Ewe'?", choices: ["Sheep", "Goat", "Lamb", "Flock"], correctIndex: 0, explanation: "'Sheep' is the species name that covers both the Ram and the Ewe." },
    { question: "What is the gender-neutral term for 'Bull/Cow'?", choices: ["Cattle", "Oxen", "Bovine", "All of the above"], correctIndex: 3, explanation: "Cattle, Oxen, and Bovine are all terms used to describe the group or species without specifying gender." },
    { question: "What is the feminine of 'Dog' (specifically)?", choices: ["Bitch", "Dam", "Queen", "Sow"], correctIndex: 0, explanation: "While 'Dog' is the common term, the technical term for a female canine is 'Bitch'." },
    { question: "What is the masculine of 'Bitch'?", choices: ["Dog", "Sire", "Hound", "Wolf"], correctIndex: 0, explanation: "In breeding terms, 'Bitch' is female, and 'Dog' is the specific term for the male." },
    { question: "What is a 'Gelding'?", choices: ["Male horse (castrated)", "Female horse", "Young horse", "Wild horse"], correctIndex: 0, explanation: "A 'Gelding' is a specific term for a male horse that has been castrated (cannot reproduce)." },

    // 41-50: Human Titles (Advanced)
    { question: "Feminine of 'Czar'?", choices: ["Czarina", "Queen", "Empress", "Duchess"], correctIndex: 0, explanation: "'Czar' (or Tsar) was the Russian Emperor; his wife was the 'Czarina'." },
    { question: "Masculine of 'Sultana'?", choices: ["Sultan", "King", "Prince", "Rajah"], correctIndex: 0, explanation: "'Sultana' is a female royal title in Arabic history; the male is 'Sultan'." },
    { question: "Feminine of 'Maharajah'?", choices: ["Maharani", "Princess", "Rani", "Lady"], correctIndex: 0, explanation: "'Maharajah' is a Great King in India. 'Maharani' is the Great Queen." },
    { question: "Masculine of 'Signora'?", choices: ["Signor", "Sir", "Monsieur", "Senor"], correctIndex: 0, explanation: "'Signora' is Italian for Mrs. or Madam. The male equivalent is 'Signor'." },
    { question: "Feminine of 'Fiancé'?", choices: ["Fiancée", "Bride", "Wife", "Betrothed"], correctIndex: 0, explanation: "This word comes from French. 'Fiancé' (one 'e') is the male; 'Fiancée' (two 'e's) is the female." },
    { question: "Masculine of 'Blonde'?", choices: ["Blond", "Brunette", "Dark", "Fair"], correctIndex: 0, explanation: "Technically, 'Blond' (no 'e') is for males, and 'Blonde' (with 'e') is for females, though many people use them interchangeably now." },
    { question: "Feminine of 'Executor'?", choices: ["Executrix", "Executer", "Executioner", "Executor"], correctIndex: 0, explanation: "In legal terms, an 'Executor' is a man appointed to handle a will. A woman is traditionally called an 'Executrix'." },
    { question: "Masculine of 'Testatrix'?", choices: ["Testator", "Testament", "Tester", "Testy"], correctIndex: 0, explanation: "A 'Testatrix' is a woman who makes a will. A man who makes a will is a 'Testator'." },
    { question: "Feminine of 'Administrator'?", choices: ["Administratrix", "Admin", "Secretary", "Boss"], correctIndex: 0, explanation: "Similar to Executor, the legal feminine form uses the Latin suffix '-trix', becoming 'Administratrix'." },
    { question: "Masculine of 'Belle'?", choices: ["Beau", "Boy", "Handsome", "Gent"], correctIndex: 0, explanation: "'Belle' means a beautiful woman. 'Beau' is the French term for a male admirer or boyfriend." }
  ],

  super: [
    // 1-15: Obscure Animal Genders
    { question: "What is the masculine of 'Pen' (Swan)?", choices: ["Cob", "Drake", "Gander", "Buck"], correctIndex: 0, explanation: "This is a rare one! A male swan is a 'Cob', and a female swan is a 'Pen'." },
    { question: "What is the feminine of 'Cob'?", choices: ["Pen", "Hen", "Sow", "Goose"], correctIndex: 0, explanation: "As mentioned, the partner of the male Cob (swan) is the female 'Pen'." },
    { question: "What is the masculine of 'Jill' (Ferret/Polecat)?", choices: ["Hob", "Jack", "Tom", "Buck"], correctIndex: 0, explanation: "A female ferret is a 'Jill'. The male is called a 'Hob'." },
    { question: "What is the feminine of 'Tod' (Fox)?", choices: ["Vixen", "Sow", "Doe", "Jill"], correctIndex: 0, explanation: "'Tod' is another term for a male fox. The female fox is a 'Vixen'." },
    { question: "What is the masculine of 'Tabby' (Cat)?", choices: ["Tom", "Gib", "Jack", "Boar"], correctIndex: 0, explanation: "A 'Tabby' is often associated with female cats (or Queens). The male cat is famously called a 'Tom'." },
    { question: "What is the feminine of 'Hart' (Red Deer)?", choices: ["Hind", "Doe", "Roe", "Sow"], correctIndex: 0, explanation: "A 'Hart' is a male red deer over 5 years old. The female red deer is called a 'Hind'." },
    { question: "What is the masculine of 'Hind'?", choices: ["Hart", "Stag", "Buck", "Bull"], correctIndex: 0, explanation: "Since 'Hind' is the female red deer, the male is the 'Hart'." },
    { question: "What is the masculine of 'Jenny' (Donkey)?", choices: ["Jack", "Tom", "Dick", "Harry"], correctIndex: 0, explanation: "A female donkey is a 'Jenny'. The male is a 'Jack' (hence, Jackass)." },
    { question: "What is the feminine of 'Billy' (Goat)?", choices: ["Nanny", "Doe", "Sow", "Ewe"], correctIndex: 0, explanation: "A male goat is a 'Billy'. The female is a 'Nanny'." },
    { question: "What is the masculine of 'Nanny' (Goat)?", choices: ["Billy", "Buck", "Ram", "Bull"], correctIndex: 0, explanation: "The partner of the Nanny goat is the 'Billy' goat." },
    { question: "What is the gender of a 'Drone' (Bee)?", choices: ["Male", "Female", "Neuter", "Common"], correctIndex: 0, explanation: "In a bee colony, the Queen and Workers are female. The 'Drones' are the males." },
    { question: "What is the feminine of 'Tiercel' (Hawk)?", choices: ["Formel", "Hen", "Sow", "Pen"], correctIndex: 0, explanation: "In falconry, 'Tiercel' is the male hawk. 'Formel' is the archaic term for the female." },
    { question: "What is the masculine of 'Cygnet'?", choices: ["None (Young Swan)", "Cob", "Pen", "Drake"], correctIndex: 0, explanation: "'Cygnet' refers to a young swan of *either* sex, so there is no specific masculine distinction until they grow up." },
    { question: "What is the feminine of 'Buck' (Rabbit)?", choices: ["Doe", "Sow", "Hen", "Vixen"], correctIndex: 0, explanation: "Like deer, rabbits use 'Buck' for males and 'Doe' for females." },
    { question: "What is the masculine of 'Queen' (Cat)?", choices: ["Tom", "King", "Sire", "Jack"], correctIndex: 0, explanation: "A female cat used for breeding is a 'Queen'. The male is a 'Tom'." },

    // 16-30: Archaic, Foreign, & Legal Terms
    { question: "Masculine of 'Marquise'?", choices: ["Marquis", "Duke", "Earl", "Baron"], correctIndex: 0, explanation: "'Marquise' is a French noble title for a woman. The male equivalent is 'Marquis'." },
    { question: "Feminine of 'Viceroy'?", choices: ["Vicereine", "Queen", "Countess", "Lady"], correctIndex: 0, explanation: "A 'Viceroy' is a ruler acting for the king. His wife (or a female ruler) is a 'Vicereine'." },
    { question: "Masculine of 'Abbess'?", choices: ["Abbot", "Monk", "Priest", "Bishop"], correctIndex: 0, explanation: "An 'Abbess' is the female head of an abbey. The male head is an 'Abbot'." },
    { question: "Feminine of 'Prior'?", choices: ["Prioress", "Nun", "Sister", "Mother"], correctIndex: 0, explanation: "A 'Prior' leads a priory (men). The female equivalent is a 'Prioress'." },
    { question: "Masculine of 'Spinster' (Historically)?", choices: ["Spinner", "Bachelor", "Weaver", "Husband"], correctIndex: 0, explanation: "Originally, 'Spinner' was the male who spun thread, and 'Spinster' was the female. Later, Spinster came to mean an unmarried woman." },
    { question: "Feminine of 'Prosecutor'?", choices: ["Prosecutrix", "Prosecuter", "Lawyer", "Attorney"], correctIndex: 0, explanation: "In archaic legal English, the female prosecutor was a 'Prosecutrix'." },
    { question: "Masculine of 'Aviatrix'?", choices: ["Aviator", "Pilot", "Flyer", "Captain"], correctIndex: 0, explanation: "In the early days of flight, female pilots were 'Aviatrixes'. The male (and now general) term is 'Aviator'." },
    { question: "Feminine of 'Equerry'?", choices: ["None/Equerry", "Equerress", "Lady", "Dame"], correctIndex: 0, explanation: "An 'Equerry' is an officer of the royal household. There is no distinct feminine form; women holding the post are also called Equerries." },
    { question: "Masculine of 'Prima Donna'?", choices: ["Primo Uomo", "Tenor", "Singer", "Star"], correctIndex: 0, explanation: "'Prima Donna' is the 'First Lady' of the opera. The leading male singer is the 'Primo Uomo' (First Man)." },
    { question: "Feminine of 'Alumnus'?", choices: ["Alumna", "Alumni", "Alumnae", "Graduate"], correctIndex: 0, explanation: "This is Latin. 'Alumnus' is one male graduate. 'Alumna' is one female graduate." },
    { question: "Plural Masculine of 'Alumnus'?", choices: ["Alumni", "Alumnus", "Alumnas", "Alumnae"], correctIndex: 0, explanation: "The plural for a group of male graduates (or mixed gender) is 'Alumni' (pronounced Alum-nye)." },
    { question: "Plural Feminine of 'Alumna'?", choices: ["Alumnae", "Alumnas", "Alumni", "Alumnus"], correctIndex: 0, explanation: "The plural for a group of female graduates is 'Alumnae' (pronounced Alum-nee)." },
    { question: "Masculine of 'Sorcerer'?", choices: ["Sorcerer", "Witch", "Wizard", "Warlock"], correctIndex: 0, explanation: "Technically, 'Sorcerer' is the male term. The female is 'Sorceress'." },
    { question: "Feminine of 'Prophet'?", choices: ["Prophetess", "Seer", "Visionary", "Lady"], correctIndex: 0, explanation: "A male predictor is a Prophet; a female is a 'Prophetess'." },
    { question: "Masculine of 'Diva'?", choices: ["Divo", "Singer", "Tenor", "Star"], correctIndex: 0, explanation: "'Diva' usually refers to a female goddess or star. The rare male equivalent is 'Divo'." },

    // 31-40: Complex Grammar & Agreement
    { question: "Agreement: 'Neither the manager nor the employees could find ____ keys.'", choices: ["their", "his", "her", "its"], correctIndex: 0, explanation: "The rule is: Agree with the noun closest to the verb. 'Employees' is plural, so we use 'their'." },
    { question: "Agreement: 'Neither the employees nor the manager could find ____ keys.'", choices: ["his or her", "their", "its", "our"], correctIndex: 0, explanation: "Here, the closer noun is 'manager' (singular). So we use 'his or her' (or just his/her depending on the manager's gender)." },
    { question: "Agreement: 'The jury gave ____ verdict.'", choices: ["its", "their", "his", "her"], correctIndex: 0, explanation: "When a collective noun like 'jury' acts as a single unit (giving one verdict), it is singular. We use 'its'." },
    { question: "Agreement: 'The jury were divided in ____ opinions.'", choices: ["their", "its", "his", "her"], correctIndex: 0, explanation: "When the group members disagree, they are acting as individuals. Therefore, we use the plural 'their'." },
    { question: "The phrase 'Gentle reader' historically addresses:", choices: ["Both genders", "Men only", "Women only", "Critics"], correctIndex: 0, explanation: "This is a classic literary address used by authors to speak to anyone reading the book, regardless of gender." },
    { question: "Which is an 'Epicene' noun?", choices: ["Teacher", "King", "Queen", "Boy"], correctIndex: 0, explanation: "Epicene nouns have a single form that covers both sexes. 'Teacher' is epicene; the others are gender-specific." },
    { question: "What is the gender of 'Baby' when the sex is unknown?", choices: ["Neuter (It)", "Masculine", "Feminine", "Common"], correctIndex: 0, explanation: "While a baby is a person, English grammar allows using 'It' (neuter) if the sex is unknown or irrelevant to the conversation." },
    { question: "In the sentence 'Man is mortal', 'Man' functions as:", choices: ["Generic masculine (Humanity)", "Specific masculine", "Neuter", "Adjective"], correctIndex: 0, explanation: "In this philosophical context, 'Man' stands for all of Humankind, not just males." },
    { question: "Which sentence avoids gender bias best?", choices: ["A nurse must be patient with her patients.", "A nurse must be patient with his patients.", "Nurses must be patient with their patients.", "A nurse must be patient with its patients."], correctIndex: 2, explanation: "Making the subject plural ('Nurses') allows you to use 'their' naturally, avoiding the clumsy 'his or her' or the biased 'her'." },
    { question: "The pronoun 'One' (e.g., One must do one's best) is:", choices: ["Gender neutral", "Masculine", "Feminine", "Neuter"], correctIndex: 0, explanation: "'One' is a formal, impersonal pronoun that applies to any person, male or female." },

    // 41-50: Etymology & Niche Trivia
    { question: "The suffix '-ess' (e.g., Actress) is of what origin?", choices: ["French/Latin", "German", "Greek", "Spanish"], correctIndex: 0, explanation: "This suffix came from the French '-esse' and Latin '-issa', used to denote female roles." },
    { question: "The suffix '-ster' (e.g., Spinster) was originally:", choices: ["Feminine", "Masculine", "Neuter", "Common"], correctIndex: 0, explanation: "In Old English, '-ster' was strictly a feminine suffix (e.g., 'Bakester' was a female baker). Today, words like 'Gangster' are masculine/common." },
    { question: "Which word is traditionally feminine but applies to males metaphorically?", choices: ["Siren", "Bull", "Ram", "Stag"], correctIndex: 0, explanation: "A 'Siren' is a mythical female creature. However, we sometimes call a tempting person (of any gender) a siren metaphorically, though it remains a feminine noun." },
    { question: "The word 'Widower' is unique because:", choices: ["It derives from the feminine form", "It is shorter than the feminine", "It has no feminine", "It is Latin"], correctIndex: 0, explanation: "This is a linguistic oddity! Usually, the male word is the base (Prince -> Princess). Here, the female 'Widow' is the base, and the male 'Widower' adds the suffix." },
    { question: "In grammar, English has 'Natural Gender', whereas Spanish has:", choices: ["Grammatical Gender", "Neutral Gender", "Common Gender", "No Gender"], correctIndex: 0, explanation: "In Spanish, objects like tables have gender (la mesa = feminine). In English, gender is determined by biology (Natural Gender)—tables are just 'it'." },
    { question: "Which ship name is masculine?", choices: ["The Bismarck", "The Titanic", "The Queen Mary", "The Elizabeth"], correctIndex: 0, explanation: "While ships are almost always 'She', the German battleship Bismarck was referred to as 'He' by its captain to emphasize its power." },
    { question: "What is the masculine of 'Amazon' (Warrior woman)?", choices: ["No specific equivalent", "Warrior", "Soldier", "Spartan"], correctIndex: 0, explanation: "There is no direct male equivalent because 'Amazon' refers specifically to a mythical tribe of women warriors." },
    { question: "The term 'Hero' was originally masculine. The feminine is 'Heroine'. Today 'Hero' is:", choices: ["Common gender", "Still masculine only", "Neuter", "Archaic"], correctIndex: 0, explanation: "Language evolves. Today, women are frequently called 'Heroes', making the word effectively common gender in modern usage." },
    { question: "What is the feminine of 'Tsar'?", choices: ["Tsarina", "Tsara", "Queen", "Duchess"], correctIndex: 0, explanation: "A 'Tsar' is a Russian Emperor; his wife is a 'Tsarina'." },
    { question: "Justice' is often personified as a woman holding scales. Why?", choices: ["Based on Roman Goddess Justitia", "Based on Greek God Zeus", "Arbitrary choice", "Because women are judges"], correctIndex: 0, explanation: "This tradition comes from Roman mythology, where 'Justitia' was the Goddess of Justice." }
  ]
};
