// questions/conjunctions.js

// 1. Safety Check
window.VERBAL_QUESTION_BANK = window.VERBAL_QUESTION_BANK || {};

// 2. Inject Data
window.VERBAL_QUESTION_BANK["conjunctions"] = {

  // ============================================
  // LEVEL 1: BEGINNER (50 Items)
  // ============================================
  beginner: [
    { question: "I like coffee ___ I don't like tea.", options: ["and", "but", "or", "so"], answer: "but", explanation: "“But” is used to show a contrast between liking coffee and not liking tea." },
    { question: "She is tired ___ she will go to bed early.", options: ["so", "but", "or", "yet"], answer: "so", explanation: "“So” introduces the result of being tired: she will go to bed early." },
    { question: "Do you want rice ___ noodles for lunch?", options: ["and", "but", "or", "so"], answer: "or", explanation: "“Or” is used when giving a choice between two options." },
    { question: "My brother ___ my sister are both teachers.", options: ["or", "and", "but", "so"], answer: "and", explanation: "“And” joins two equal nouns that share the same verb." },
    { question: "It was raining, ___ we stayed inside.", options: ["and", "but", "so", "or"], answer: "so", explanation: "“So” shows the result of the rain: they stayed inside." },
    { question: "She studied hard, ___ she still failed the test.", options: ["so", "and", "or", "yet"], answer: "yet", explanation: "“Yet” shows an unexpected contrast between studying hard and failing." },
    { question: "I will call you ___ I arrive home.", options: ["although", "because", "when", "so"], answer: "when", explanation: "“When” is a time conjunction that shows at what time the call will happen." },
    { question: "We stayed at home ___ it was very cold outside.", options: ["because", "when", "if", "or"], answer: "because", explanation: "“Because” introduces the reason for staying at home." },
    { question: "You can have tea ___ coffee, but not both.", options: ["and", "or", "so", "yet"], answer: "or", explanation: "“Or” is used to express one option or the other, not both." },
    { question: "She wanted to go out, ___ she had a lot of work to do.", options: ["and", "so", "but", "or"], answer: "but", explanation: "“But” shows contrast between wanting to go out and having work to do." },
    { question: "I will help you ___ you ask politely.", options: ["so", "if", "but", "when"], answer: "if", explanation: "“If” introduces a condition: help will be given only if you ask politely." },
    { question: "He went to the store ___ bought some milk.", options: ["or", "but", "and", "so"], answer: "and", explanation: "“And” adds another action that he did after going to the store." },
    { question: "She didn't call me ___ send me a message.", options: ["or", "and", "but", "so"], answer: "or", explanation: "In a negative sentence, “or” is used to join two actions that did not happen." },
    { question: "I stayed awake ___ I was very sleepy.", options: ["so", "because", "although", "and"], answer: "although", explanation: "“Although” shows contrast between being sleepy and staying awake." },
    { question: "We can go to the park ___ we can watch a movie at home.", options: ["so", "and", "or", "but"], answer: "or", explanation: "“Or” is used to present two possible activities." },
    { question: "She went to the doctor ___ she was feeling sick.", options: ["because", "so", "or", "but"], answer: "because", explanation: "“Because” introduces the reason for going to the doctor." },
    { question: "He is poor ___ he is honest.", options: ["so", "and", "but", "or"], answer: "but", explanation: "“But” contrasts being poor with being honest." },
    { question: "I will wait here ___ you come back.", options: ["until", "so", "or", "but"], answer: "until", explanation: "“Until” shows the time limit for the waiting." },
    { question: "Close the window ___ the room will be cold.", options: ["because", "and", "or", "but"], answer: "or", explanation: "“Or” shows what will happen if the window is not closed." },
    { question: "He was hungry, ___ he ate a sandwich.", options: ["and", "but", "so", "or"], answer: "so", explanation: "“So” introduces the result of being hungry." },
    { question: "She sings ___ she plays the guitar.", options: ["and", "because", "or", "but"], answer: "and", explanation: "“And” joins two actions she can do." },
    { question: "We cannot start the meeting ___ the manager arrives.", options: ["when", "while", "until", "so"], answer: "until", explanation: "“Until” shows that the meeting can start only after the manager arrives." },
    { question: "He likes to read ___ to write stories.", options: ["or", "and", "but", "so"], answer: "and", explanation: "“And” is used because he likes both activities." },
    { question: "I went to bed early ___ I was very tired.", options: ["but", "although", "because", "or"], answer: "because", explanation: "“Because” gives the reason for going to bed early." },
    { question: "We can stay here ___ we can go home now.", options: ["and", "but", "or", "so"], answer: "or", explanation: "“Or” presents the choice between staying and going home." },
    { question: "The baby cried ___ he was hungry.", options: ["so", "because", "but", "and"], answer: "because", explanation: "“Because” introduces the reason the baby cried." },
    { question: "I brought an umbrella ___ it might rain.", options: ["because", "although", "if", "and"], answer: "because", explanation: "“Because” explains why the umbrella was brought." },
    { question: "She smiled ___ she was happy.", options: ["but", "because", "or", "yet"], answer: "because", explanation: "“Because” gives the reason for her smile." },
    { question: "He failed the exam, ___ he didn't study enough.", options: ["so", "but", "because", "or"], answer: "because", explanation: "“Because” shows the reason for failing the exam." },
    { question: "I will call you ___ I finish my work.", options: ["or", "when", "but", "so"], answer: "when", explanation: "“When” indicates the time the call will be made." },
    { question: "She was sick, ___ she still went to school.", options: ["so", "but", "because", "or"], answer: "but", explanation: "“But” contrasts being sick with still going to school." },
    { question: "You must hurry, ___ you will miss the bus.", options: ["or", "and", "because", "but"], answer: "or", explanation: "“Or” shows the negative result if you do not hurry." },
    { question: "He is tall ___ strong.", options: ["or", "so", "and", "but"], answer: "and", explanation: "“And” adds another positive quality to describe him." },
    { question: "I stayed at home ___ it was raining heavily.", options: ["so", "because", "but", "or"], answer: "because", explanation: "“Because” gives the reason for staying at home." },
    { question: "They were tired, ___ they continued working.", options: ["so", "but", "because", "and"], answer: "but", explanation: "“But” shows contrast between being tired and continuing to work." },
    { question: "She passed the test ___ she studied every day.", options: ["because", "so", "or", "but"], answer: "because", explanation: "“Because” explains why she passed the test." },
    { question: "I will help you ___ I can.", options: ["but", "if", "when", "or"], answer: "if", explanation: "“If” expresses the condition under which help will be given." },
    { question: "We will go out ___ the rain stops.", options: ["if", "although", "because", "or"], answer: "if", explanation: "“If” shows that going out depends on the rain stopping." },
    { question: "I like apples ___ I don't like bananas.", options: ["and", "but", "or", "so"], answer: "but", explanation: "“But” is used to contrast two different preferences." },
    { question: "She cleaned the house ___ cooked dinner.", options: ["or", "but", "so", "and"], answer: "and", explanation: "“And” joins two actions she did." },
    { question: "He didn't go to work ___ he was sick.", options: ["because", "so", "but", "or"], answer: "because", explanation: "“Because” explains why he didn't go to work." },
    { question: "I will come to your party ___ I finish my project on time.", options: ["if", "so", "and", "yet"], answer: "if", explanation: "“If” shows that coming to the party depends on finishing the project." },
    { question: "She was scared, ___ she entered the dark room.", options: ["so", "but", "because", "or"], answer: "but", explanation: "“But” contrasts being scared with still entering the dark room." },
    { question: "He opened the window ___ fresh air could come in.", options: ["so", "but", "or", "and"], answer: "so", explanation: "“So” shows the purpose or result of opening the window." },
    { question: "We will stay home ___ watch a movie.", options: ["so", "and", "but", "or"], answer: "and", explanation: "“And” connects two actions they will do at home." },
    { question: "She can speak English ___ Spanish.", options: ["but", "or", "and", "so"], answer: "and", explanation: "“And” joins the two languages she can speak." },
    { question: "You should study hard, ___ you might fail the exam.", options: ["and", "or", "so", "because"], answer: "or", explanation: "“Or” introduces the possible consequence if you do not study." },
    { question: "He was late ___ there was heavy traffic.", options: ["but", "because", "so", "and"], answer: "because", explanation: "“Because” gives the reason he was late." },
    { question: "She didn't buy the dress ___ it was too expensive.", options: ["because", "so", "but", "or"], answer: "because", explanation: "“Because” explains why she didn't buy the dress." },
    { question: "I like swimming ___ I don't like diving.", options: ["and", "or", "but", "so"], answer: "but", explanation: "“But” contrasts liking one activity and not liking the other." }
  ],

  // ============================================
  // LEVEL 2: INTERMEDIATE (50 Items)
  // ============================================
  intermediate: [
    { question: "_______ he was very tired, he continued working.", options: ["Although", "Because", "So", "If"], answer: "Although", explanation: "“Although” is used to show contrast between being tired and still continuing to work." },
    { question: "She will pass the exam _______ she studies hard.", options: ["if", "although", "because", "so"], answer: "if", explanation: "“If” introduces the condition that she must study hard to pass." },
    { question: "He stayed at home _______ the weather was bad.", options: ["because", "although", "while", "until"], answer: "because", explanation: "“Because” gives the reason why he stayed at home." },
    { question: "_______ the rain stopped, the children went outside.", options: ["When", "Because", "If", "So"], answer: "When", explanation: "“When” is a time conjunction showing that the children went out after the rain stopped." },
    { question: "He likes to read novels _______ he dislikes poetry.", options: ["but", "and", "so", "or"], answer: "but", explanation: "“But” shows contrast between liking novels and disliking poetry." },
    { question: "You cannot enter the building _______ you have an ID card.", options: ["unless", "because", "although", "so"], answer: "unless", explanation: "“Unless” means “except if,” showing the condition for entering." },
    { question: "We left early _______ we could avoid the traffic.", options: ["so that", "although", "while", "if"], answer: "so that", explanation: "“So that” expresses purpose: they left early in order to avoid traffic." },
    { question: "_______ he was not feeling well, he went to work.", options: ["Although", "Because", "So", "If"], answer: "Although", explanation: "“Although” shows contrast between not feeling well and still going to work." },
    { question: "She did not attend the meeting _______ she had an emergency.", options: ["because", "although", "so", "if"], answer: "because", explanation: "“Because” gives the reason why she did not attend the meeting." },
    { question: "We waited in the lobby _______ the manager arrived.", options: ["until", "because", "if", "so"], answer: "until", explanation: "“Until” indicates that the waiting continued up to the time the manager arrived." },
    { question: "He speaks softly _______ everyone can understand him.", options: ["so that", "although", "because", "if"], answer: "so that", explanation: "“So that” shows purpose: he speaks softly in order for everyone to understand." },
    { question: "She was angry _______ she did not show it.", options: ["but", "so", "because", "or"], answer: "but", explanation: "“But” contrasts being angry with not showing it." },
    { question: "You can borrow my laptop _______ you return it tomorrow.", options: ["provided that", "although", "because", "so"], answer: "provided that", explanation: "“Provided that” sets a condition that must be met to borrow the laptop." },
    { question: "I will not go out _______ it stops raining.", options: ["until", "so", "because", "although"], answer: "until", explanation: "“Until” shows that going out depends on the rain stopping." },
    { question: "She smiled _______ she was nervous inside.", options: ["although", "because", "so", "if"], answer: "although", explanation: "“Although” shows contrast between smiling and feeling nervous." },
    { question: "He missed the flight _______ he left home late.", options: ["because", "although", "until", "if"], answer: "because", explanation: "“Because” explains why he missed the flight." },
    { question: "_______ you work hard, you will achieve your goals.", options: ["If", "Because", "Although", "While"], answer: "If", explanation: "“If” introduces the condition for achieving goals." },
    { question: "The students were quiet _______ the teacher was speaking.", options: ["while", "because", "so", "although"], answer: "while", explanation: "“While” indicates two actions happening at the same time." },
    { question: "She did not get the job _______ she had good qualifications.", options: ["although", "because", "so", "if"], answer: "although", explanation: "“Although” shows contrast between not getting the job and having good qualifications." },
    { question: "Bring your umbrella _______ it rains later.", options: ["in case", "because", "until", "although"], answer: "in case", explanation: "“In case” is used to show precaution for a possible future situation." },
    { question: "He stayed calm _______ everyone around him was panicking.", options: ["while", "because", "so", "if"], answer: "while", explanation: "“While” contrasts his calm behavior with others panicking at the same time." },
    { question: "We can go hiking _______ the weather is good tomorrow.", options: ["if", "although", "because", "so"], answer: "if", explanation: "“If” shows hiking is conditional on good weather." },
    { question: "He failed the test _______ he did not review the lessons.", options: ["because", "although", "while", "so"], answer: "because", explanation: "“Because” shows the reason he failed." },
    { question: "I will join the contest _______ my parents allow me.", options: ["if", "because", "when", "although"], answer: "if", explanation: "“If” introduces the condition of parental permission." },
    { question: "The child kept crying _______ he lost his toy.", options: ["because", "although", "so", "if"], answer: "because", explanation: "“Because” explains why the child kept crying." },
    { question: "He turned off his phone _______ he could focus on his work.", options: ["so that", "although", "because", "if"], answer: "so that", explanation: "“So that” expresses the purpose of turning off his phone." },
    { question: "We arrived early _______ we could get good seats.", options: ["so that", "because", "although", "if"], answer: "so that", explanation: "“So that” shows that arriving early was done to get good seats." },
    { question: "She kept studying _______ she was very tired.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” emphasizes the contrast between being tired and continuing to study." },
    { question: "I will not sign the document _______ I read it carefully.", options: ["until", "because", "so", "although"], answer: "until", explanation: "“Until” indicates that signing will happen only after reading carefully." },
    { question: "He took a taxi _______ he would not be late.", options: ["so that", "because", "although", "if"], answer: "so that", explanation: "“So that” shows purpose: he took a taxi to avoid being late." },
    { question: "She cannot leave the office _______ her boss gives permission.", options: ["until", "because", "so", "although"], answer: "until", explanation: "“Until” shows that leaving is not allowed before permission is given." },
    { question: "_______ he apologized, she refused to forgive him.", options: ["Although", "Because", "So", "If"], answer: "Although", explanation: "“Although” shows contrast between him apologizing and her refusing to forgive." },
    { question: "We need to hurry _______ we will miss the beginning of the show.", options: ["or", "and", "because", "although"], answer: "or", explanation: "“Or” shows the negative consequence of not hurrying." },
    { question: "You should check your answers _______ you submit the test.", options: ["before", "so", "although", "because"], answer: "before", explanation: "“Before” indicates the correct order of actions." },
    { question: "He will call you _______ he arrives at the hotel.", options: ["when", "because", "if", "although"], answer: "when", explanation: "“When” is used to show the time he will call." },
    { question: "She saved money _______ she could buy a new laptop.", options: ["so that", "because", "although", "if"], answer: "so that", explanation: "“So that” shows the purpose of saving money." },
    { question: "They canceled the picnic _______ it started to rain.", options: ["because", "although", "so", "if"], answer: "because", explanation: "“Because” explains why the picnic was canceled." },
    { question: "You will not succeed _______ you work hard.", options: ["unless", "because", "when", "so"], answer: "unless", explanation: "“Unless” means “if not,” showing the need to work hard to succeed." },
    { question: "She stayed calm _______ the situation was very serious.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” shows strong contrast between calmness and seriousness." },
    { question: "He reads the news every day _______ he can stay informed.", options: ["so that", "because", "although", "if"], answer: "so that", explanation: "“So that” expresses the purpose of reading the news." },
    { question: "We will stay indoors _______ the storm is over.", options: ["until", "because", "if", "although"], answer: "until", explanation: "“Until” indicates staying indoors up to the end of the storm." },
    { question: "He looks confident _______ he is actually very nervous.", options: ["although", "because", "so", "if"], answer: "although", explanation: "“Although” shows contrast between appearance and reality." },
    { question: "She will not speak _______ she is asked a question.", options: ["unless", "because", "when", "so"], answer: "unless", explanation: "“Unless” means she will speak only if she is asked." },
    { question: "_______ the lights went out, we continued the meeting.", options: ["Even though", "Because", "So", "If"], answer: "Even though", explanation: "“Even though” shows contrast between the power outage and continuing the meeting." },
    { question: "I will lend you the book _______ you promise to return it.", options: ["if", "because", "although", "so"], answer: "if", explanation: "“If” shows that lending the book depends on the promise." },
    { question: "He whispered _______ he did not want to wake the baby.", options: ["because", "so", "although", "if"], answer: "because", explanation: "“Because” gives the reason he whispered." },
    { question: "She goes jogging every morning _______ it is raining.", options: ["unless", "if", "although", "because"], answer: "unless", explanation: "“Unless” here means she will jog except when it is raining." },
    { question: "We turned down the music _______ the neighbors complained.", options: ["because", "although", "so", "if"], answer: "because", explanation: "“Because” shows the reason for turning down the music." },
    { question: "He went to bed early _______ he had to get up at 4 a.m.", options: ["because", "although", "so", "if"], answer: "because", explanation: "“Because” explains why he went to bed early." },
    { question: "She wore a coat _______ it was very cold outside.", options: ["because", "although", "so", "if"], answer: "because", explanation: "“Because” introduces the reason for wearing a coat." }
  ],

  // ============================================
  // LEVEL 3: ADVANCED (50 Items)
  // ============================================
  advanced: [
    { question: "She is not only intelligent _______ also very hardworking.", options: ["but", "and", "or", "so"], answer: "but", explanation: "The correct correlative pattern is “not only … but also ….”" },
    { question: "Either you submit the report today _______ you will miss the deadline.", options: ["or", "and", "but", "so"], answer: "or", explanation: "“Either … or” is used to show two alternative possibilities." },
    { question: "She is both kind _______ generous.", options: ["and", "or", "but", "so"], answer: "and", explanation: "“Both … and” is the correct correlative pair." },
    { question: "Neither the manager _______ the staff knew about the change.", options: ["nor", "or", "and", "but"], answer: "nor", explanation: "“Neither … nor” is the correct correlative conjunction pair." },
    { question: "Whether you agree _______ not, the decision has been made.", options: ["or", "and", "but", "so"], answer: "or", explanation: "“Whether … or” is used to show two alternatives, both leading to the same result." },
    { question: "He speaks slowly _______ clearly, so everyone understands him.", options: ["and", "or", "but", "yet"], answer: "and", explanation: "“And” joins two positive adverbs describing how he speaks." },
    { question: "The project is behind schedule, _______ we need to work overtime.", options: ["so", "but", "because", "although"], answer: "so", explanation: "“So” introduces the necessary consequence of the delay." },
    { question: "The plan was excellent; _______ it was not executed properly.", options: ["however", "because", "so", "if"], answer: "however", explanation: "“However” shows contrast between an excellent plan and poor execution." },
    { question: "He is older _______ he looks.", options: ["than", "as", "like", "while"], answer: "than", explanation: "“Than” is used in comparisons after comparative adjectives like “older.”" },
    { question: "She acted _______ she owned the place.", options: ["as if", "because", "so that", "until"], answer: "as if", explanation: "“As if” introduces a comparison to an unreal or imaginary situation." },
    { question: "He works _______ he were the only person responsible.", options: ["as if", "because", "although", "so"], answer: "as if", explanation: "“As if” shows he behaves in a way that suggests something that is not literally true." },
    { question: "Hardly had he arrived _______ the meeting started.", options: ["when", "than", "before", "because"], answer: "when", explanation: "In this inversion pattern, “Hardly … when” is the correct pair." },
    { question: "Scarcely had she finished speaking _______ the phone rang.", options: ["when", "than", "because", "if"], answer: "when", explanation: "The fixed expression is “Scarcely … when” or “Scarcely … had … when.”" },
    { question: "No sooner had they left _______ it began to rain.", options: ["than", "when", "because", "if"], answer: "than", explanation: "“No sooner … than” is the correct correlative conjunction pattern." },
    { question: "He is as tall _______ his brother.", options: ["as", "than", "like", "while"], answer: "as", explanation: "“As … as” is the correct pattern for equal comparison." },
    { question: "She did not know _______ to laugh or cry.", options: ["whether", "either", "neither", "both"], answer: "whether", explanation: "“Whether” introduces two possible reactions: to laugh or cry." },
    { question: "He worked hard _______ he could support his family.", options: ["so that", "because", "although", "if"], answer: "so that", explanation: "“So that” expresses his purpose in working hard." },
    { question: "We will finish the task, _______ it takes all night.", options: ["even if", "because", "so", "when"], answer: "even if", explanation: "“Even if” emphasizes determination despite a possible difficulty." },
    { question: "He refused to quit, _______ the situation seemed hopeless.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” highlights strong contrast between appearance and his decision." },
    { question: "She kept quiet _______ she disagreed with the decision.", options: ["although", "because", "so", "if"], answer: "although", explanation: "“Although” shows a contrast between disagreement and remaining quiet." },
    { question: "You must follow the instructions exactly, _______ you may damage the device.", options: ["or", "and", "so", "but"], answer: "or", explanation: "“Or” introduces the negative consequence of not following instructions." },
    { question: "Not only did she finish early, _______ she also helped her teammates.", options: ["but", "and", "so", "or"], answer: "but", explanation: "The correct form is “Not only … but also …” even with inversion." },
    { question: "He stayed home, _______ he was feeling unwell.", options: ["for", "so", "and", "yet"], answer: "for", explanation: "Here, “for” is a coordinating conjunction meaning “because.”" },
    { question: "I will call you later _______ I have some free time.", options: ["when", "because", "although", "so"], answer: "when", explanation: "“When” introduces the time condition for calling." },
    { question: "She hid the letter _______ no one could find it.", options: ["so that", "because", "although", "if"], answer: "so that", explanation: "“So that” explains the purpose of hiding the letter." },
    { question: "He acts _______ he knew everything.", options: ["as if", "because", "so that", "until"], answer: "as if", explanation: "“As if” is used to show behavior that suggests something that is not necessarily true." },
    { question: "She sings better _______ she did last year.", options: ["than", "as", "like", "while"], answer: "than", explanation: "“Than” is used after a comparative form like “better.”" },
    { question: "You can pay in cash _______ by credit card.", options: ["or", "and", "but", "so"], answer: "or", explanation: "“Or” expresses a choice between two payment methods." },
    { question: "Both the manager _______ the employees attended the training.", options: ["and", "or", "but", "so"], answer: "and", explanation: "“Both … and” joins two subjects that share the same verb." },
    { question: "Neither the documents _______ the samples have arrived.", options: ["nor", "or", "and", "but"], answer: "nor", explanation: "“Neither … nor” joins two negative items." },
    { question: "He failed the test, _______ he had studied all night.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” shows strong contrast between studying and failing." },
    { question: "We stayed indoors _______ the storm passed.", options: ["until", "because", "if", "although"], answer: "until", explanation: "“Until” shows that they stayed inside up to the time the storm ended." },
    { question: "He did not complain, _______ he was clearly disappointed.", options: ["although", "because", "so", "if"], answer: "although", explanation: "“Although” contrasts his lack of complaint with his disappointment." },
    { question: "You will receive the bonus _______ you meet all your targets.", options: ["if", "because", "although", "so"], answer: "if", explanation: "“If” gives the condition to receive the bonus." },
    { question: "She speaks Spanish _______ fluent English.", options: ["as well as", "and", "or", "but"], answer: "as well as", explanation: "“As well as” adds extra information in a slightly more formal way than “and.”" },
    { question: "He stayed late at the office _______ he could finish the report.", options: ["so that", "although", "because", "if"], answer: "so that", explanation: "“So that” expresses his purpose in staying late." },
    { question: "The results were worse _______ we expected.", options: ["than", "as", "like", "while"], answer: "than", explanation: "“Than” is the conjunction used in comparisons with comparatives like “worse.”" },
    { question: "We will start the meeting _______ everyone has arrived.", options: ["after", "because", "if", "although"], answer: "after", explanation: "“After” shows the time relationship between arrival and starting the meeting." },
    { question: "He talks as though he _______ the answer.", options: ["knew", "knows", "know", "knowing"], answer: "knew", explanation: "“As though” or “as if” are often followed by a past form to show an unreal situation." },
    { question: "The more you practice, _______ you will improve.", options: ["the more", "so", "than", "because"], answer: "the more", explanation: "In this structure, “The more … the more …” is the correct correlative pattern." },
    { question: "She decided to stay, _______ it was getting late.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” shows contrast between the time and her decision to stay." },
    { question: "He will continue working _______ he finishes the project.", options: ["until", "because", "if", "although"], answer: "until", explanation: "“Until” shows that he will work up to the time the project is finished." },
    { question: "She did not stop practicing, _______ she was tired.", options: ["although", "because", "so", "if"], answer: "although", explanation: "“Although” shows contrast between her tiredness and her continuous practice." },
    { question: "We will travel next month _______ we can get a discount.", options: ["so that", "because", "although", "if"], answer: "so that", explanation: "“So that” expresses the purpose of traveling next month." },
    { question: "He stayed positive, _______ the situation was difficult.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” emphasizes contrast between his attitude and the situation." },
    { question: "We arrived late _______ the traffic was heavy.", options: ["because", "although", "so", "if"], answer: "because", explanation: "“Because” introduces the reason for arriving late." },
    { question: "She will join us for dinner _______ she finishes work early.", options: ["if", "because", "although", "so"], answer: "if", explanation: "“If” shows a condition for her joining the dinner." },
    { question: "He did not hesitate, _______ he knew the risks.", options: ["although", "because", "so", "if"], answer: "although", explanation: "“Although” contrasts his lack of hesitation with his knowledge of the risks." },
    { question: "You may leave early _______ you finish all your tasks.", options: ["provided that", "because", "although", "so"], answer: "provided that", explanation: "“Provided that” introduces a condition that must be satisfied." },
    { question: "She speaks more confidently now _______ she used to.", options: ["than", "as", "like", "while"], answer: "than", explanation: "“Than” is used to compare her current confidence with the past." }
  ],

  // ============================================
  // LEVEL 4: EXPERT (50 Items) - Subtle Logic
  // ============================================
  expert: [
    { question: "Not only was the presentation informative, _______ it was also entertaining.", options: ["but", "and", "so", "or"], answer: "but", explanation: "The correct correlative pattern is “not only … but also ….”" },
    { question: "He kept working _______ everyone else had already gone home.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” shows strong contrast between his action and others leaving." },
    { question: "We will approve your request _______ you submit the required documents.", options: ["provided that", "although", "because", "so"], answer: "provided that", explanation: "“Provided that” introduces a strict condition for approval." },
    { question: "She behaves _______ she had never made a mistake in her life.", options: ["as if", "because", "so that", "before"], answer: "as if", explanation: "“As if” is used to describe behavior that suggests something that is not really true." },
    { question: "No sooner had the meeting ended _______ they began to argue.", options: ["than", "when", "because", "if"], answer: "than", explanation: "The fixed expression is “No sooner … than ….”" },
    { question: "Hardly had he finished his speech _______ the audience started clapping.", options: ["when", "than", "because", "if"], answer: "when", explanation: "“Hardly … when …” is the correct combination in this inversion structure." },
    { question: "Scarcely had we sat down _______ the lights went out.", options: ["when", "than", "because", "if"], answer: "when", explanation: "“Scarcely … when …” is a common pattern to show something happened immediately after." },
    { question: "The more you read, _______ you understand complex texts.", options: ["the better", "so", "than", "because"], answer: "the better", explanation: "The structure is “The more … the better …” to show proportional increase." },
    { question: "He refused to give up, _______ the odds were against him.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” emphasizes a strong contrast between the odds and his decision." },
    { question: "You will continue to receive support _______ you follow the guidelines carefully.", options: ["as long as", "because", "although", "so"], answer: "as long as", explanation: "“As long as” expresses a condition that must continue to be met." },
    { question: "She treated him _______ he were her own brother.", options: ["as if", "because", "so that", "until"], answer: "as if", explanation: "“As if” introduces a comparison to an unreal or imagined situation." },
    { question: "He is not so much careless _______ he is overconfident.", options: ["as", "than", "like", "while"], answer: "as", explanation: "The expression “not so much A as B” means B is a more accurate description." },
    { question: "He left early, _______ he had a long journey ahead of him.", options: ["for", "so", "but", "or"], answer: "for", explanation: "Here, “for” is a coordinating conjunction meaning “because.”" },
    { question: "We must act now, _______ it may be too late.", options: ["or", "and", "so", "because"], answer: "or", explanation: "“Or” presents the negative consequence of not acting now." },
    { question: "He decided to stay, _______ his friends encouraged him to leave.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” shows contrast between advice and his decision." },
    { question: "She kept smiling, _______ she was deeply worried.", options: ["although", "because", "so", "if"], answer: "although", explanation: "“Although” contrasts her outward expression with her inner feelings." },
    { question: "You will not understand the problem _______ you look at it from another angle.", options: ["unless", "because", "when", "so"], answer: "unless", explanation: "“Unless” means “if not,” showing a necessary change in perspective." },
    { question: "She will attend the seminar _______ it is directly related to her work.", options: ["only if", "because", "so", "although"], answer: "only if", explanation: "“Only if” introduces a strict condition for attending." },
    { question: "They continued the project _______ they had lost their main sponsor.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” shows contrast between losing the sponsor and continuing." },
    { question: "He speaks to everyone _______ they were old friends.", options: ["as if", "because", "so that", "when"], answer: "as if", explanation: "“As if” is used to describe a way of speaking that suggests familiarity." },
    { question: "She will not sign the contract _______ her lawyer reviews it.", options: ["until", "because", "so", "if"], answer: "until", explanation: "“Until” shows that signing will only happen after the review." },
    { question: "We decided to postpone the event _______ the weather forecast was terrible.", options: ["because", "although", "so", "if"], answer: "because", explanation: "“Because” introduces the reason for postponing." },
    { question: "He kept working, _______ he was clearly exhausted.", options: ["though", "because", "so", "if"], answer: "though", explanation: "“Though” at the end or middle of a sentence can show contrast." },
    { question: "They will support the proposal, _______ it benefits the community.", options: ["provided that", "because", "although", "so"], answer: "provided that", explanation: "“Provided that” sets a condition for their support." },
    { question: "She writes more clearly now _______ she did before.", options: ["than", "as", "like", "while"], answer: "than", explanation: "“Than” is used in comparative structures like “more clearly than ….”" },
    { question: "_______ we leave now, we will arrive before sunset.", options: ["If", "Because", "Although", "So"], answer: "If", explanation: "“If” introduces a time/condition relationship for arriving before sunset." },
    { question: "He answered as though he _______ all the details.", options: ["knew", "knows", "knowing", "know"], answer: "knew", explanation: "“As though” often takes a past form to suggest an unreal or uncertain situation." },
    { question: "The committee will approve the plan _______ it meets the safety standards.", options: ["if", "because", "although", "so"], answer: "if", explanation: "“If” expresses the condition for approval." },
    { question: "She remained calm, _______ the situation was becoming dangerous.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” emphasizes the contrast between calmness and danger." },
    { question: "He continued to smile _______ everything was going wrong.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” highlights strong contrast." },
    { question: "You can stay here _______ you keep the noise down.", options: ["as long as", "because", "although", "so"], answer: "as long as", explanation: "“As long as” shows a continuing condition for staying." },
    { question: "He worked as a volunteer _______ he gained valuable experience.", options: ["and", "so", "but", "or"], answer: "and", explanation: "“And” joins two positive outcomes of the same situation." },
    { question: "She spoke softly, _______ the baby was sleeping.", options: ["for", "so", "but", "or"], answer: "for", explanation: "“For” explains the reason, similar to “because.”" },
    { question: "He will accept the job offer _______ the terms are fair.", options: ["provided that", "because", "although", "so"], answer: "provided that", explanation: "“Provided that” is used for conditions that must be satisfied." },
    { question: "She writes not so much to earn money _______ to express herself.", options: ["as", "than", "like", "while"], answer: "as", explanation: "“Not so much A as B” means the second part is the main reason." },
    { question: "He studies hard, _______ he knows the exam will be difficult.", options: ["for", "so", "but", "or"], answer: "for", explanation: "“For” here means “because,” giving the reason for studying." },
    { question: "They will not proceed _______ they receive written confirmation.", options: ["unless", "because", "when", "so"], answer: "unless", explanation: "“Unless” means they will proceed only if they receive confirmation." },
    { question: "He walks as though he _______ all the time in the world.", options: ["had", "has", "having", "have"], answer: "had", explanation: "“As though” often uses a past form to suggest an unreal impression." },
    { question: "We will continue the discussion _______ everyone agrees on a solution.", options: ["until", "because", "if", "so"], answer: "until", explanation: "“Until” indicates that the discussion will last up to a certain point in time." },
    { question: "She stayed behind _______ she could finish the paperwork.", options: ["so that", "because", "although", "if"], answer: "so that", explanation: "“So that” expresses her purpose in staying behind." },
    { question: "We will go for a walk _______ the rain stops.", options: ["after", "because", "although", "so"], answer: "after", explanation: "“After” shows the time sequence of events." },
    { question: "He joined the organization _______ he believed in its mission.", options: ["because", "although", "so", "if"], answer: "because", explanation: "“Because” gives the reason for joining." },
    { question: "They listened carefully _______ they could understand every detail.", options: ["so that", "because", "although", "if"], answer: "so that", explanation: "“So that” expresses purpose for listening carefully." },
    { question: "He answered every question, _______ some of them were very difficult.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” contrasts his success with the difficulty of the questions." },
    { question: "The team succeeded _______ many people had doubted them.", options: ["though", "because", "so", "if"], answer: "though", explanation: "“Though” here highlights contrast between doubt and success." },
    { question: "We decided to stay indoors _______ the storm passed.", options: ["until", "because", "if", "although"], answer: "until", explanation: "“Until” shows they stayed inside up to the end of the storm." },
    { question: "He will continue his studies _______ he finds a suitable opportunity abroad.", options: ["unless", "because", "when", "so"], answer: "unless", explanation: "“Unless” means he will only stop if he finds an opportunity abroad." },
    { question: "She kept working, _______ she had already reached her target.", options: ["even though", "because", "so", "if"], answer: "even though", explanation: "“Even though” shows contrast between achieving the target and still working." },
    { question: "He will take the job _______ the salary is competitive.", options: ["provided that", "because", "although", "so"], answer: "provided that", explanation: "“Provided that” introduces a condition for accepting the job." },
    { question: "The more they insisted, _______ he became.", options: ["the more stubborn", "so", "than", "because"], answer: "the more stubborn", explanation: "The correlative pattern “The more … the more …” shows a proportional relationship." }
  ]
};
