// questions/analogy.js

// Make sure the global object exists
window.VERBAL_QUESTION_BANK = window.VERBAL_QUESTION_BANK || {};

window.VERBAL_QUESTION_BANK["analogy"] = {

  // ==========================================
  // LEVEL 1: BEGINNER (50 Items)
  // Focus: Basic relationships, daily objects, simple opposites
  // ==========================================
  beginner: [
    { question: "SUN : DAY :: MOON : _______", options: ["Night", "Star", "Sky", "Light"], answer: "Night", explanation: "The sun appears in the day; the moon appears in the night." },
    { question: "WINTER : COLD :: SUMMER : _______", options: ["Hot", "Warm", "Snow", "Rain"], answer: "Hot", explanation: "Winter is cold; summer is hot." },
    { question: "BIRD : FLY :: FISH : _______", options: ["Walk", "Swim", "Run", "Jump"], answer: "Swim", explanation: "A bird flies; a fish swims." },
    { question: "KEYBOARD : TYPE :: MOUSE : _______", options: ["Click", "Scroll", "Point", "Move"], answer: "Click", explanation: "You type with a keyboard; you click with a mouse." },
    { question: "BREAD : BAKER :: MEAT : _______", options: ["Butcher", "Cook", "Farmer", "Hunter"], answer: "Butcher", explanation: "A baker sells bread; a butcher sells meat." },
    { question: "OCEAN : SALT WATER :: LAKE : _______", options: ["Fresh Water", "Deep Water", "Cold Water", "Blue Water"], answer: "Fresh Water", explanation: "Oceans have salt water; lakes usually have fresh water." },
    { question: "LIBRARY : BOOKS :: MUSEUM : _______", options: ["Artifacts", "People", "Animals", "Food"], answer: "Artifacts", explanation: "A library houses books; a museum houses artifacts." },
    { question: "CHAIR : SIT :: BED : _______", options: ["Sleep", "Lie", "Rest", "Jump"], answer: "Sleep", explanation: "You sit on a chair; you sleep on a bed." },
    { question: "DOCTOR : STETHOSCOPE :: PAINTER : _______", options: ["Brush", "Telescope", "Thermometer", "Scale"], answer: "Brush", explanation: "A doctor uses a stethoscope; a painter uses a brush." },
    { question: "RED : STOP :: GREEN : _______", options: ["Go", "Wait", "Slow", "Caution"], answer: "Go", explanation: "Red light means stop; green light means go." },
    { question: "FLOUR : BREAD :: GRAPES : _______", options: ["Wine", "Juice", "Jam", "Vinegar"], answer: "Wine", explanation: "Flour is used to make bread; grapes are used to make wine." },
    { question: "WHEEL : CAR :: PROPELLER : _______", options: ["Airplane", "Bicycle", "Train", "Boat"], answer: "Airplane", explanation: "A wheel moves a car; a propeller moves an airplane." },
    { question: "HIGH : LOW :: FAST : _______", options: ["Slow", "Quick", "Rapid", "Swift"], answer: "Slow", explanation: "High is the opposite of low; fast is the opposite of slow." },
    { question: "FORK : EAT :: COMB : _______", options: ["Hair", "Head", "Style", "Brush"], answer: "Hair", explanation: "A fork is used for eating; a comb is used for hair." },
    { question: "BATTERY : ENERGY :: TANK : _______", options: ["Water", "Fuel", "Air", "Oil"], answer: "Fuel", explanation: "A battery holds energy; a tank holds fuel." },
    { question: "FARMER : CROPS :: FISHERMAN : _______", options: ["Fish", "Net", "Boat", "Water"], answer: "Fish", explanation: "A farmer harvests crops; a fisherman catches fish." },
    { question: "UMBRELLA : RAIN :: SUNGLASSES : _______", options: ["Sun", "Snow", "Wind", "Dark"], answer: "Sun", explanation: "An umbrella protects from rain; sunglasses protect from the sun." },
    { question: "PILOT : AIRPLANE :: CAPTAIN : _______", options: ["Ship", "Team", "Army", "Car"], answer: "Ship", explanation: "A pilot commands an airplane; a captain commands a ship." },
    { question: "LEAVES : TREE :: PETALS : _______", options: ["Flower", "Stem", "Root", "Branch"], answer: "Flower", explanation: "Leaves are part of a tree; petals are part of a flower." },
    { question: "HARD : SOFT :: LOUD : _______", options: ["Quiet", "Noisy", "Sound", "Silent"], answer: "Quiet", explanation: "Hard is the opposite of soft; loud is the opposite of quiet." },
    { question: "MAP : LOCATION :: CALENDAR : _______", options: ["Date", "Time", "Year", "Month"], answer: "Date", explanation: "A map shows location; a calendar shows the date." },
    { question: "BANK : MONEY :: HOTEL : _______", options: ["Guests", "Food", "Rooms", "Service"], answer: "Guests", explanation: "A bank holds money; a hotel holds/hosts guests." },
    { question: "SCISSORS : CUT :: GLUE : _______", options: ["Stick", "Break", "Color", "Write"], answer: "Stick", explanation: "Scissors are used to cut; glue is used to stick." },
    { question: "MORNING : SUNRISE :: EVENING : _______", options: ["Sunset", "Moon", "Stars", "Dark"], answer: "Sunset", explanation: "Sunrise happens in the morning; sunset happens in the evening." },
    { question: "SWEET : CANDY :: SALTY : _______", options: ["Chips", "Chocolate", "Cake", "Ice Cream"], answer: "Chips", explanation: "Candy is sweet; chips are salty." },
    { question: "CAT : MEOW :: DOG : _______", options: ["Bark", "Roar", "Hiss", "Moo"], answer: "Bark", explanation: "A cat meows; a dog barks." },
    { question: "EARS : HEAR :: EYES : _______", options: ["See", "Smell", "Touch", "Taste"], answer: "See", explanation: "Ears are for hearing; eyes are for seeing." },
    { question: "FOOT : SHOE :: HAND : _______", options: ["Glove", "Sock", "Hat", "Ring"], answer: "Glove", explanation: "A shoe is worn on the foot; a glove is worn on the hand." },
    { question: "TEACHER : STUDENT :: DOCTOR : _______", options: ["Patient", "Nurse", "Hospital", "Medicine"], answer: "Patient", explanation: "A teacher teaches a student; a doctor treats a patient." },
    { question: "CARPENTER : HAMMER :: CHEF : _______", options: ["Knife", "Saw", "Drill", "Wrench"], answer: "Knife", explanation: "A carpenter uses a hammer; a chef uses a knife." },
    { question: "HAPPY : SMILE :: SAD : _______", options: ["Frown", "Laugh", "Jump", "Sing"], answer: "Frown", explanation: "You smile when happy; you frown when sad." },
    { question: "MOUNTAIN : HIGH :: VALLEY : _______", options: ["Low", "Deep", "Flat", "Wide"], answer: "Low", explanation: "A mountain is high; a valley is low." },
    { question: "FIRE : HOT :: ICE : _______", options: ["Cold", "Wet", "Hard", "Solid"], answer: "Cold", explanation: "Fire is hot; ice is cold." },
    { question: "PEN : WRITE :: BRUSH : _______", options: ["Paint", "Draw", "Color", "Sketch"], answer: "Paint", explanation: "A pen is used to write; a brush is used to paint." },
    { question: "ONE : SINGLE :: TWO : _______", options: ["Double", "Triple", "Couple", "Pair"], answer: "Double", explanation: "Single means one; double means two." },
    { question: "RING : FINGER :: NECKLACE : _______", options: ["Neck", "Wrist", "Ear", "Ankle"], answer: "Neck", explanation: "A ring goes on a finger; a necklace goes on a neck." },
    { question: "COW : HERD :: BIRD : _______", options: ["Flock", "Pack", "School", "Swarm"], answer: "Flock", explanation: "A group of cows is a herd; a group of birds is a flock." },
    { question: "CAR : GARAGE :: PLANE : _______", options: ["Hangar", "Airport", "Sky", "Runway"], answer: "Hangar", explanation: "A car is stored in a garage; a plane is stored in a hangar." },
    { question: "SNAKE : REPTILE :: FROG : _______", options: ["Amphibian", "Mammal", "Insect", "Bird"], answer: "Amphibian", explanation: "A snake is a reptile; a frog is an amphibian." },
    { question: "NOSE : SMELL :: TONGUE : _______", options: ["Taste", "Touch", "Hear", "See"], answer: "Taste", explanation: "The nose is for smelling; the tongue is for tasting." },
    { question: "AUTHOR : BOOK :: ARTIST : _______", options: ["Painting", "Song", "Movie", "Poem"], answer: "Painting", explanation: "An author creates a book; an artist creates a painting." },
    { question: "WALK : LEGS :: FLY : _______", options: ["Wings", "Arms", "Hands", "Feet"], answer: "Wings", explanation: "You walk with legs; you fly with wings." },
    { question: "HUNGRY : FOOD :: THIRSTY : _______", options: ["Water", "Bread", "Sleep", "Rest"], answer: "Water", explanation: "When hungry you need food; when thirsty you need water." },
    { question: "DAY : LIGHT :: NIGHT : _______", options: ["Dark", "Sun", "Moon", "Star"], answer: "Dark", explanation: "Day is light; night is dark." },
    { question: "CIRCLE : ROUND :: SQUARE : _______", options: ["Boxy", "Flat", "Long", "Oval"], answer: "Boxy", explanation: "A circle is round; a square is boxy (has corners)." },
    { question: "FATHER : PARENT :: SISTER : _______", options: ["Sibling", "Mother", "Brother", "Friend"], answer: "Sibling", explanation: "A father is a parent; a sister is a sibling." },
    { question: "SCHOOL : LEARN :: GYM : _______", options: ["Exercise", "Sleep", "Eat", "Read"], answer: "Exercise", explanation: "You go to school to learn; you go to a gym to exercise." },
    { question: "PAPER : TREE :: WOOL : _______", options: ["Sheep", "Cow", "Cotton", "Plant"], answer: "Sheep", explanation: "Paper comes from trees; wool comes from sheep." },
    { question: "LEFT : RIGHT :: UP : _______", options: ["Down", "Bottom", "Low", "Under"], answer: "Down", explanation: "Left is opposite of right; up is opposite of down." },
    { question: "CLOCK : TIME :: THERMOMETER : _______", options: ["Temperature", "Heat", "Weather", "Cold"], answer: "Temperature", explanation: "A clock measures time; a thermometer measures temperature." }
  ],

  // ==========================================
  // LEVEL 2: INTERMEDIATE (50 Items)
  // Focus: Logic, categories, slight vocabulary increase
  // ==========================================
  intermediate: [
    { question: "ANALOGY : COMPARISON :: METAPHOR : _______", options: ["Symbol", "Similarity", "Contrast", "Example"], answer: "Similarity", explanation: "An analogy is a type of comparison; a metaphor is a figure of speech denoting similarity." },
    { question: "GILLS : FISH :: LUNGS : _______", options: ["Mammals", "Birds", "Humans", "Animals"], answer: "Mammals", explanation: "Fish breathe with gills; mammals breathe with lungs." },
    { question: "INSULATOR : ELECTRICITY :: REFRIGERATOR : _______", options: ["Heat", "Cold", "Food", "Water"], answer: "Heat", explanation: "An insulator keeps out electricity; a refrigerator keeps out heat." },
    { question: "PEDAL : BICYCLE :: RUDDER : _______", options: ["Boat", "Car", "Plane", "Train"], answer: "Boat", explanation: "A pedal moves a bike; a rudder steers a boat." },
    { question: "COMPASS : DIRECTION :: BAROMETER : _______", options: ["Pressure", "Temperature", "Humidity", "Wind"], answer: "Pressure", explanation: "A compass measures direction; a barometer measures atmospheric pressure." },
    { question: "SYMPHONY : ORCHESTRA :: SOLO : _______", options: ["Musician", "Singer", "Instrument", "Performance"], answer: "Musician", explanation: "A symphony is performed by an orchestra; a solo is performed by one musician." },
    { question: "FOSSIL : PALAEONTOLOGIST :: ARTIFACT : _______", options: ["Archaeologist", "Historian", "Geologist", "Biologist"], answer: "Archaeologist", explanation: "Palaeontologists study fossils; archaeologists study artifacts." },
    { question: "MOLECULE : ATOM :: SOLAR SYSTEM : _______", options: ["Planet", "Star", "Sun", "Galaxy"], answer: "Planet", explanation: "A molecule is made of atoms; a solar system is made of planets." },
    { question: "VACCINE : IMMUNITY :: VITAMIN : _______", options: ["Health", "Strength", "Energy", "Growth"], answer: "Health", explanation: "A vaccine promotes immunity; a vitamin promotes health." },
    { question: "METAMORPHOSIS : CHANGE :: EVOLUTION : _______", options: ["Development", "Revolution", "Creation", "Destruction"], answer: "Development", explanation: "Metamorphosis is a form of change; evolution is a form of development." },
    { question: "CENSUS : POPULATION :: INVENTORY : _______", options: ["Goods", "Money", "Land", "Buildings"], answer: "Goods", explanation: "A census counts population; an inventory counts goods." },
    { question: "LEVER : LIFT :: PULLEY : _______", options: ["Raise", "Push", "Turn", "Cut"], answer: "Raise", explanation: "A lever helps lift; a pulley helps raise/hoist." },
    { question: "HIBERNATION : WINTER :: MIGRATION : _______", options: ["Season", "Climate", "Food", "Habitat"], answer: "Season", explanation: "Hibernation happens in winter; migration happens according to season." },
    { question: "PHOTOSYNTHESIS : PLANTS :: RESPIRATION : _______", options: ["Living Things", "Animals", "Humans", "Mammals"], answer: "Living Things", explanation: "Plants do photosynthesis; all living things do respiration." },
    { question: "ECLIPSE : CELESTIAL :: EARTHQUAKE : _______", options: ["Geological", "Atmospheric", "Oceanic", "Cosmic"], answer: "Geological", explanation: "An eclipse is a celestial event; an earthquake is a geological event." },
    { question: "SYNONYM : SIMILAR :: ANTONYM : _______", options: ["Opposite", "Different", "Same", "Related"], answer: "Opposite", explanation: "Synonyms are similar; antonyms are opposite." },
    { question: "FRACTION : DECIMAL :: PERCENTAGE : _______", options: ["Ratio", "Proportion", "Whole", "Part"], answer: "Ratio", explanation: "Fractions and decimals represent parts; percentage is a specific type of ratio." },
    { question: "GRAVITY : ATTRACTION :: MAGNETISM : _______", options: ["Polarity", "Repulsion", "Force", "Field"], answer: "Polarity", explanation: "Gravity is an attractive force; magnetism is defined by polarity (attract/repel)." },
    { question: "METAPHOR : IMPLIED :: SIMILE : _______", options: ["Direct", "Stated", "Obvious", "Explicit"], answer: "Direct", explanation: "A metaphor is an implied comparison; a simile is a direct comparison (using like/as)." },
    { question: "ECOSYSTEM : ENVIRONMENT :: ORGANISM : _______", options: ["Habitat", "Home", "Cell", "Body"], answer: "Habitat", explanation: "An ecosystem is the environment; an organism lives in a habitat." },
    { question: "CATALYST : REACTION :: ENZYME : _______", options: ["Digestion", "Growth", "Movement", "Breathing"], answer: "Digestion", explanation: "A catalyst speeds up a reaction; an enzyme speeds up biological processes like digestion." },
    { question: "INSULIN : SUGAR :: HEMOGLOBIN : _______", options: ["Oxygen", "Blood", "Iron", "Cells"], answer: "Oxygen", explanation: "Insulin regulates sugar; hemoglobin carries oxygen." },
    { question: "RENAISSANCE : REBIRTH :: ENLIGHTENMENT : _______", options: ["Reason", "Knowledge", "Light", "Education"], answer: "Reason", explanation: "The Renaissance was an age of rebirth; The Enlightenment was an age of reason." },
    { question: "MONARCH : ROYALTY :: PRESIDENT : _______", options: ["Republic", "Democracy", "Government", "Leadership"], answer: "Republic", explanation: "A monarch rules a kingdom/royalty; a president leads a republic." },
    { question: "HYPOTHESIS : THEORY :: EXPERIMENT : _______", options: ["Proof", "Test", "Idea", "Law"], answer: "Proof", explanation: "A hypothesis is a guess; an experiment provides proof." },
    { question: "ARCHITECT : BLUEPRINT :: COMPOSER : _______", options: ["Score", "Song", "Music", "Instrument"], answer: "Score", explanation: "An architect makes a blueprint; a composer makes a score." },
    { question: "REFEREE : GAME :: MODERATOR : _______", options: ["Debate", "Meeting", "School", "Vote"], answer: "Debate", explanation: "A referee oversees a game; a moderator oversees a debate." },
    { question: "CHAPTER : BOOK :: SCENE : _______", options: ["Play", "Movie", "Act", "Song"], answer: "Play", explanation: "A chapter is part of a book; a scene is part of a play." },
    { question: "BOTANY : PLANTS :: ZOOLOGY : _______", options: ["Animals", "Zoos", "Life", "Nature"], answer: "Animals", explanation: "Botany is the study of plants; zoology is the study of animals." },
    { question: "WALLET : MONEY :: TANK : _______", options: ["Gas", "Water", "Air", "Liquid"], answer: "Gas", explanation: "A wallet holds money; a tank holds gas/fuel." },
    { question: "ORCHARD : FRUIT :: VINEYARD : _______", options: ["Grapes", "Wine", "Alcohol", "Farm"], answer: "Grapes", explanation: "An orchard grows fruit; a vineyard grows grapes." },
    { question: "SOLDIER : REGIMENT :: STAR : _______", options: ["Constellation", "Galaxy", "Sky", "Universe"], answer: "Constellation", explanation: "A soldier is part of a regiment; a star is part of a constellation." },
    { question: "DAM : WATER :: LEVEE : _______", options: ["Flood", "River", "Stream", "Lake"], answer: "Flood", explanation: "A dam controls water flow; a levee prevents a flood." },
    { question: "MICROSCOPE : BACTERIA :: TELESCOPE : _______", options: ["Stars", "Sky", "Distance", "Moon"], answer: "Stars", explanation: "A microscope views bacteria; a telescope views stars." },
    { question: "SHEEP : FLOCK :: WOLVES : _______", options: ["Pack", "Herd", "Group", "Gang"], answer: "Pack", explanation: "A group of sheep is a flock; a group of wolves is a pack." },
    { question: "NOVELIST : BOOK :: PLAYWRIGHT : _______", options: ["Drama", "Script", "Stage", "Actor"], answer: "Drama", explanation: "A novelist writes a book; a playwright writes a drama." },
    { question: "SNAKE : HISS :: LION : _______", options: ["Roar", "Growl", "Purr", "Bark"], answer: "Roar", explanation: "A snake hisses; a lion roars." },
    { question: "THERMOMETER : TEMPERATURE :: ODOMETER : _______", options: ["Distance", "Speed", "Fuel", "Heat"], answer: "Distance", explanation: "Thermometer measures temperature; odometer measures distance." },
    { question: "HUNGER : FOOD :: EXHAUSTION : _______", options: ["Sleep", "Rest", "Energy", "Run"], answer: "Sleep", explanation: "Food cures hunger; sleep cures exhaustion." },
    { question: "BRICK : WALL :: CELL : _______", options: ["Tissue", "Body", "Organ", "Blood"], answer: "Tissue", explanation: "Bricks make a wall; cells make tissue." },
    { question: "QUAKE : TREMBLE :: FIRE : _______", options: ["Burn", "Heat", "Smoke", "Flame"], answer: "Burn", explanation: "Quake means to tremble; fire means to burn (action)." },
    { question: "INNOCENT : GUILTY :: IGNORANT : _______", options: ["Knowledgeable", "Smart", "Wise", "Educated"], answer: "Knowledgeable", explanation: "Innocent is opposite of guilty; ignorant is opposite of knowledgeable." },
    { question: "AIRPLANE : HANGAR :: SHIP : _______", options: ["Dock", "Port", "Ocean", "Anchor"], answer: "Dock", explanation: "An airplane parks in a hangar; a ship parks at a dock." },
    { question: "LUNG : OXYGEN :: STOMACH : _______", options: ["Food", "Digestion", "Acid", "Nutrients"], answer: "Food", explanation: "Lungs process oxygen; the stomach processes food." },
    { question: "SAND : GLASS :: TREE : _______", options: ["Paper", "Wood", "Leaf", "Forest"], answer: "Paper", explanation: "Sand is used to make glass; trees are used to make paper." },
    { question: "DILIGENT : LAZY :: BRAVE : _______", options: ["Cowardly", "Fearful", "Scared", "Weak"], answer: "Cowardly", explanation: "Diligent is opposite of lazy; brave is opposite of cowardly." },
    { question: "POET : VERSE :: SCULPTOR : _______", options: ["Statue", "Stone", "Chisel", "Art"], answer: "Statue", explanation: "A poet creates verse; a sculptor creates a statue." },
    { question: "COTTON : SOFT :: ROCK : _______", options: ["Hard", "Heavy", "Rough", "Gray"], answer: "Hard", explanation: "Cotton is characteristically soft; a rock is characteristically hard." },
    { question: "KEYBOARD : COMPUTER :: REMOTE : _______", options: ["Television", "Control", "Battery", "Button"], answer: "Television", explanation: "A keyboard controls a computer; a remote controls a television." },
    { question: "CHEF : RESTAURANT :: TEACHER : _______", options: ["Classroom", "School", "Desk", "Books"], answer: "Classroom", explanation: "A chef works in a restaurant; a teacher works in a classroom." }
  ],

  // ==========================================
  // LEVEL 3: ADVANCED (50 Items)
  // Focus: Abstract concepts, specialized fields
  // ==========================================
  advanced: [
    { question: "CATHARSIS : EMOTION :: THERAPY : _______", options: ["Healing", "Treatment", "Medicine", "Recovery"], answer: "Healing", explanation: "Catharsis is the release of emotion; therapy is the process of healing." },
    { question: "PARADOX : CONTRADICTION :: DILEMMA : _______", options: ["Choice", "Problem", "Solution", "Question"], answer: "Choice", explanation: "A paradox involves a contradiction; a dilemma involves a difficult choice." },
    { question: "UTOPIA : IDEAL :: DYSTOPIA : _______", options: ["Nightmare", "Reality", "Future", "Past"], answer: "Nightmare", explanation: "Utopia is an ideal world; dystopia is a nightmare world." },
    { question: "EMPIRICAL : OBSERVATION :: THEORETICAL : _______", options: ["Speculation", "Proof", "Experiment", "Data"], answer: "Speculation", explanation: "Empirical is based on observation; theoretical is based on speculation or ideas." },
    { question: "DICHOTOMY : DIVISION :: SPECTRUM : _______", options: ["Range", "Color", "Light", "Scale"], answer: "Range", explanation: "A dichotomy divides into two; a spectrum offers a continuous range." },
    { question: "AMBIVALENCE : UNCERTAINTY :: CONVICTION : _______", options: ["Certainty", "Belief", "Faith", "Trust"], answer: "Certainty", explanation: "Ambivalence is a state of uncertainty; conviction is a state of certainty." },
    { question: "ANACHRONISM : TIME :: ANOMALY : _______", options: ["Pattern", "Rule", "System", "Order"], answer: "Pattern", explanation: "An anachronism is an error in time; an anomaly is a break from the pattern." },
    { question: "SUBJECTIVE : PERSONAL :: OBJECTIVE : _______", options: ["Impersonal", "General", "Universal", "Factual"], answer: "Impersonal", explanation: "Subjective is personal bias; objective is impersonal fact." },
    { question: "METACOGNITION : THINKING :: METANARRATIVE : _______", options: ["Narrative", "Story", "History", "Plot"], answer: "Narrative", explanation: "Metacognition is thinking about thinking; metanarrative is a narrative about narrative." },
    { question: "SYMBIOSIS : MUTUALISM :: PARASITISM : _______", options: ["Exploitation", "Sharing", "Cooperation", "Competition"], answer: "Exploitation", explanation: "Symbiosis often implies mutual benefit; parasitism implies exploitation." },
    { question: "EPISTEMOLOGY : KNOWLEDGE :: ONTOLOGY : _______", options: ["Existence", "Reality", "Truth", "Being"], answer: "Existence", explanation: "Epistemology is the study of knowledge; ontology is the study of existence." },
    { question: "HEGEMONY : DOMINANCE :: AUTONOMY : _______", options: ["Independence", "Freedom", "Control", "Power"], answer: "Independence", explanation: "Hegemony is dominance over others; autonomy is independence." },
    { question: "DIALECTIC : SYNTHESIS :: DIALOGUE : _______", options: ["Understanding", "Conversation", "Argument", "Debate"], answer: "Understanding", explanation: "Dialectic logic leads to synthesis; dialogue leads to understanding." },
    { question: "PARADIGM : FRAMEWORK :: DOGMA : _______", options: ["Doctrine", "Belief", "Rule", "Law"], answer: "Doctrine", explanation: "A paradigm is a theoretical framework; dogma is established doctrine." },
    { question: "EMPATHY : UNDERSTANDING :: COMPASSION : _______", options: ["Action", "Feeling", "Kindness", "Help"], answer: "Action", explanation: "Empathy is understanding feeling; compassion is the action to help." },
    { question: "ALLEGORY : SYMBOLISM :: SATIRE : _______", options: ["Criticism", "Humor", "Irony", "Mockery"], answer: "Criticism", explanation: "Allegory uses symbolism to tell a story; satire uses humor for criticism." },
    { question: "CIRCULAR REASONING : FALLACY :: AD HOMINEM : _______", options: ["Attack", "Argument", "Logic", "Reason"], answer: "Attack", explanation: "Circular reasoning is a logical fallacy; ad hominem is a personal attack." },
    { question: "COGNITIVE DISSONANCE : CONFLICT :: CONFIRMATION BIAS : _______", options: ["Selection", "Preference", "Favoritism", "Choice"], answer: "Selection", explanation: "Cognitive dissonance is mental conflict; confirmation bias is selection of data that fits beliefs." },
    { question: "MACROECONOMICS : AGGREGATE :: MICROECONOMICS : _______", options: ["Individual", "Small", "Personal", "Specific"], answer: "Individual", explanation: "Macroeconomics looks at the aggregate (whole); microeconomics looks at the individual." },
    { question: "QUANTITATIVE : MEASUREMENT :: QUALITATIVE : _______", options: ["Description", "Quality", "Characteristic", "Attribute"], answer: "Description", explanation: "Quantitative relies on measurement; qualitative relies on description." },
    { question: "SEMANTICS : MEANING :: SYNTAX : _______", options: ["Structure", "Grammar", "Order", "Arrangement"], answer: "Structure", explanation: "Semantics is the study of meaning; syntax is the study of sentence structure." },
    { question: "PROTAGONIST : HERO :: ANTAGONIST : _______", options: ["Villain", "Enemy", "Opponent", "Rival"], answer: "Villain", explanation: "Protagonist is usually the hero; antagonist is the villain." },
    { question: "DENOTATION : LITERAL :: CONNOTATION : _______", options: ["Associative", "Figurative", "Symbolic", "Implied"], answer: "Associative", explanation: "Denotation is the literal meaning; connotation is the associative/implied meaning." },
    { question: "ANTHROPOMORPHISM : HUMAN :: ZOOMORPHISM : _______", options: ["Animal", "Nature", "God", "Machine"], answer: "Animal", explanation: "Anthropomorphism gives human traits; zoomorphism gives animal traits." },
    { question: "SOLIPSISM : SELF :: ALTRUISM : _______", options: ["Others", "Society", "Community", "World"], answer: "Others", explanation: "Solipsism is absorption in the self; altruism is concern for others." },
    { question: "CANDID : SECRETIVE :: FRANK : _______", options: ["Dishonest", "Open", "Direct", "Blunt"], answer: "Dishonest", explanation: "Candid/Frank are synonyms meaning honest; Secretive/Dishonest are opposites." },
    { question: "ODOMETER : DISTANCE :: ALTIMETER : _______", options: ["Height", "Speed", "Depth", "Time"], answer: "Height", explanation: "An odometer measures distance; an altimeter measures height." },
    { question: "VIRUS : INFLUENZA :: BACTERIA : _______", options: ["Tuberculosis", "Health", "Cell", "Microbe"], answer: "Tuberculosis", explanation: "Influenza is caused by a virus; tuberculosis is caused by bacteria." },
    { question: "FRAGILE : CRACK :: PLIABLE : _______", options: ["Bend", "Break", "Hard", "Soft"], answer: "Bend", explanation: "Fragile things crack; pliable things bend." },
    { question: "ARCHIPELAGO : ISLAND :: MOUNTAIN RANGE : _______", options: ["Peak", "Valley", "River", "Hill"], answer: "Peak", explanation: "An archipelago is a group of islands; a mountain range is a group of peaks." },
    { question: "TECTONICS : GEOLOGY :: SYNTAX : _______", options: ["Grammar", "Math", "Biology", "Physics"], answer: "Grammar", explanation: "Tectonics is part of geology; syntax is part of grammar." },
    { question: "TACITURN : TALKATIVE :: ALOOF : _______", options: ["Friendly", "Quiet", "Distant", "Cold"], answer: "Friendly", explanation: "Taciturn is opposite of talkative; aloof is opposite of friendly." },
    { question: "PHILATELIST : STAMPS :: NUMISMATIST : _______", options: ["Coins", "Books", "Maps", "Art"], answer: "Coins", explanation: "A philatelist collects stamps; a numismatist collects coins." },
    { question: "MITIGATE : SEVERE :: QUALIFY : _______", options: ["General", "Specific", "Hard", "Easy"], answer: "General", explanation: "To mitigate makes something less severe; to qualify makes a statement less general." },
    { question: "EMBEZZLE : FUNDS :: PLAGIARIZE : _______", options: ["Words", "Money", "Ideas", "Theft"], answer: "Words", explanation: "Embezzle is stealing funds; plagiarize is stealing words." },
    { question: "EPAULET : SHOULDER :: RING : _______", options: ["Finger", "Ear", "Neck", "Wrist"], answer: "Finger", explanation: "An epaulet is worn on the shoulder; a ring is worn on the finger." },
    { question: "INDIGENT : WEALTHY :: NATIVE : _______", options: ["Foreign", "Local", "Rich", "Poor"], answer: "Foreign", explanation: "Indigent is opposite of wealthy; native is opposite of foreign." },
    { question: "KEROSENE : FUEL :: WHEAT : _______", options: ["Food", "Gas", "Oil", "Grain"], answer: "Food", explanation: "Kerosene is a type of fuel; wheat is a type of food." },
    { question: "GULLIBLE : DUPED :: MALLEABLE : _______", options: ["Shaped", "Broken", "Hard", "Soft"], answer: "Shaped", explanation: "A gullible person is easily duped; a malleable object is easily shaped." },
    { question: "COBBLER : SHOES :: CARTOGRAPHER : _______", options: ["Maps", "Carts", "Books", "Houses"], answer: "Maps", explanation: "A cobbler makes shoes; a cartographer makes maps." },
    { question: "OBSEQUIOUS : FAWN :: PARSIMONIOUS : _______", options: ["Hoard", "Spend", "Give", "Share"], answer: "Hoard", explanation: "An obsequious person fawns; a parsimonious person hoards." },
    { question: "DIRGE : FUNERAL :: JINGLE : _______", options: ["Commercial", "Song", "Radio", "TV"], answer: "Commercial", explanation: "A dirge is sung at a funeral; a jingle is played in a commercial." },
    { question: "HERMIT : RECLUSE :: SYCOPHANT : _______", options: ["Flatterer", "Leader", "Teacher", "Follower"], answer: "Flatterer", explanation: "Hermit and recluse are synonyms; sycophant and flatterer are synonyms." },
    { question: "LOGIC : REASONING :: ETHICS : _______", options: ["Behavior", "Morals", "Science", "Law"], answer: "Behavior", explanation: "Logic governs reasoning; ethics governs behavior." },
    { question: "EPILOGUE : NOVEL :: DESSERT : _______", options: ["Meal", "Lunch", "Dinner", "Appetizer"], answer: "Meal", explanation: "Epilogue is the end of a novel; dessert is the end of a meal." },
    { question: "DRILL : BORE :: SIEVE : _______", options: ["Sift", "Cut", "Mix", "Hold"], answer: "Sift", explanation: "A drill is used to bore; a sieve is used to sift." },
    { question: "QUORUM : VOTE :: MAJORITY : _______", options: ["Win", "Lose", "Draw", "Elect"], answer: "Win", explanation: "A quorum is needed to vote; a majority is needed to win." },
    { question: "DICTATOR : AUTHORITY :: SNIPER : _______", options: ["Accuracy", "Gun", "War", "Skill"], answer: "Accuracy", explanation: "A dictator relies on authority; a sniper relies on accuracy." },
    { question: "YARD : LENGTH :: QUART : _______", options: ["Volume", "Weight", "Time", "Distance"], answer: "Volume", explanation: "A yard measures length; a quart measures volume." },
    { question: "IGNORANCE : KNOWLEDGE :: POVERTY : _______", options: ["Wealth", "Money", "Rich", "Poor"], answer: "Wealth", explanation: "Ignorance is lack of knowledge; poverty is lack of wealth." }
  ],

  // ==========================================
  // LEVEL 4: EXPERT (50 Items)
  // Focus: Obscure vocabulary, complex reasoning
  // (from original SUPER level)
  // ==========================================
  expert: [
    { question: "PERFIDIOUS : TRUST :: TREACHEROUS : _______", options: ["Loyalty", "Faith", "Honesty", "Honor"], answer: "Loyalty", explanation: "Perfidious means violating trust; treacherous means violating loyalty." },
    { question: "SAGACIOUS : WISDOM :: PRESCIENT : _______", options: ["Foresight", "Knowledge", "Smart", "Future"], answer: "Foresight", explanation: "Sagacious means having wisdom; prescient means having foresight." },
    { question: "VORACIOUS : HUNGER :: INSATIABLE : _______", options: ["Desire", "Thirst", "Need", "Want"], answer: "Desire", explanation: "Voracious describes extreme hunger; insatiable describes extreme desire." },
    { question: "PROLIFIC : PRODUCTIVE :: FECUND : _______", options: ["Fertile", "Rich", "Growth", "Life"], answer: "Fertile", explanation: "Prolific means productive; fecund means fertile." },
    { question: "OBSTREPEROUS : NOISY :: TURBULENT : _______", options: ["Chaotic", "Violent", "Loud", "Fast"], answer: "Chaotic", explanation: "Obstreperous describes a noisy person; turbulent describes a chaotic situation." },
    { question: "RECALCITRANT : AUTHORITY :: INTRANSIGENT : _______", options: ["Compromise", "Change", "Rules", "Law"], answer: "Compromise", explanation: "Recalcitrant resists authority; intransigent resists compromise." },
    { question: "SALUBRIOUS : HEALTH :: BENEFICIAL : _______", options: ["Advantage", "Good", "Profit", "Gain"], answer: "Advantage", explanation: "Salubrious promotes health; beneficial promotes advantage." },
    { question: "PERNICIOUS : HARM :: DETRIMENTAL : _______", options: ["Damage", "Loss", "Pain", "Injury"], answer: "Damage", explanation: "Pernicious causes harm; detrimental causes damage." },
    { question: "MAGNANIMOUS : GENEROSITY :: MUNIFICENT : _______", options: ["Largesse", "Money", "Gift", "Kindness"], answer: "Largesse", explanation: "Magnanimous is showing generosity; munificent is showing largesse (generosity with money)." },
    { question: "VERBOSE : WORDY :: LACONIC : _______", options: ["Concise", "Brief", "Short", "Silent"], answer: "Concise", explanation: "Verbose and wordy are synonyms; laconic and concise are synonyms." },
    { question: "EPHEMERAL : TEMPORARY :: EVANESCENT : _______", options: ["Fleeting", "Gone", "Short", "Quick"], answer: "Fleeting", explanation: "Ephemeral means temporary; evanescent means fleeting/vanishing." },
    { question: "UBIQUITOUS : EVERYWHERE :: OMNIPRESENT : _______", options: ["All-present", "Universal", "Global", "Total"], answer: "All-present", explanation: "Ubiquitous and everywhere are synonyms; omnipresent and all-present are synonyms." },
    { question: "ESOTERIC : OBSCURE :: ARCANE : _______", options: ["Mysterious", "Secret", "Hidden", "Dark"], answer: "Mysterious", explanation: "Esoteric means obscure; arcane means mysterious." },
    { question: "PROCRASTINATE : DELAY :: PREVARICATE : _______", options: ["Evade", "Lie", "Wait", "Stop"], answer: "Evade", explanation: "Procrastinate means to delay action; prevaricate means to evade the truth." },
    { question: "VACILLATE : DECISION :: OSCILLATE : _______", options: ["Position", "Movement", "Opinion", "Place"], answer: "Position", explanation: "Vacillate means wavering on a decision; oscillate means wavering in position." },
    { question: "CAPITULATE : SURRENDER :: ACQUIESCE : _______", options: ["Comply", "Agree", "Submit", "Give up"], answer: "Comply", explanation: "Capitulate means to surrender; acquiesce means to comply passively." },
    { question: "EXACERBATE : WORSEN :: ALLEVIATE : _______", options: ["Relieve", "Help", "Cure", "Stop"], answer: "Relieve", explanation: "Exacerbate means to worsen; alleviate means to relieve." },
    { question: "ABROGATE : LAW :: ANNUL : _______", options: ["Marriage", "Contract", "Agreement", "Vow"], answer: "Marriage", explanation: "Abrogate cancels a law; annul cancels a marriage." },
    { question: "EXTRICATE : DIFFICULTY :: DISENTANGLE : _______", options: ["Complication", "Knot", "Problem", "Mess"], answer: "Complication", explanation: "Extricate frees from difficulty; disentangle frees from complication." },
    { question: "PERPETUATE : CONTINUE :: PROPAGATE : _______", options: ["Spread", "Grow", "Live", "Move"], answer: "Spread", explanation: "Perpetuate means to make continue; propagate means to spread." },
    { question: "SUBJUGATE : CONTROL :: DOMINATE : _______", options: ["Rule", "Power", "Win", "Beat"], answer: "Rule", explanation: "Subjugate means to bring under control; dominate means to rule over." },
    { question: "CONCATENATE : LINK :: INTEGRATE : _______", options: ["Combine", "Join", "Mix", "Add"], answer: "Combine", explanation: "Concatenate means to link together; integrate means to combine." },
    { question: "DISSEMINATE : INFORMATION :: CIRCULATE : _______", options: ["News", "Paper", "Data", "Ideas"], answer: "News", explanation: "Disseminate spreads information; circulate spreads news." },
    { question: "SUBSTANTIATE : EVIDENCE :: CORROBORATE : _______", options: ["Testimony", "Proof", "Fact", "Witness"], answer: "Testimony", explanation: "Substantiate supports with evidence; corroborate supports with testimony." },
    { question: "EXTRAPOLATE : DATA :: INFER : _______", options: ["Clues", "Facts", "Ideas", "Logic"], answer: "Clues", explanation: "Extrapolate concludes from data; infer concludes from clues." },
    { question: "EPHEMERAL : ENDURING :: TRANSIENT : _______", options: ["Permanent", "Lasting", "Forever", "Stable"], answer: "Permanent", explanation: "Ephemeral is opposite of enduring; transient is opposite of permanent." },
    { question: "DIDACTIC : TEACH :: HORTATORY : _______", options: ["Urge", "Preach", "Speak", "Learn"], answer: "Urge", explanation: "Didactic intends to teach; hortatory intends to urge/encourage." },
    { question: "SOPORIFIC : SLEEP :: MNEMONIC : _______", options: ["Memory", "Mind", "Thought", "Brain"], answer: "Memory", explanation: "Soporific induces sleep; mnemonic aids memory." },
    { question: "LACONIC : WORDS :: PARSIMONIOUS : _______", options: ["Money", "Time", "Friends", "Food"], answer: "Money", explanation: "Laconic uses few words; parsimonious spends little money." },
    { question: "APOCRYPHAL : AUTHENTICITY :: NEBULOUS : _______", options: ["Definition", "Shape", "Form", "Clarify"], answer: "Definition", explanation: "Apocryphal lacks authenticity; nebulous lacks clear definition." },
    { question: "TAUTOLOGY : REPETITIVE :: OXYMORON : _______", options: ["Contradictory", "Irony", "False", "True"], answer: "Contradictory", explanation: "Tautology is repetitive; oxymoron is contradictory." },
    { question: "MERCENARY : MONEY :: VINDICTIVE : _______", options: ["Revenge", "Hate", "Anger", "Power"], answer: "Revenge", explanation: "Mercenary is motivated by money; vindictive is motivated by revenge." },
    { question: "LUGUBRIOUS : SORROWFUL :: EUPHORIC : _______", options: ["Happy", "Joyful", "Glad", "Excited"], answer: "Happy", explanation: "Lugubrious is excessively sorrowful; euphoric is excessively happy." },
    { question: "COMPENDIUM : SUMMARY :: ANTHOLOGY : _______", options: ["Collection", "Book", "Library", "Selection"], answer: "Collection", explanation: "A compendium is a summary; an anthology is a collection of works." },
    { question: "METICULOUS : DETAILS :: DOGMATIC : _______", options: ["Beliefs", "Rules", "Laws", "Faith"], answer: "Beliefs", explanation: "Meticulous focuses on details; dogmatic focuses on beliefs." },
    { question: "PALIMPSEST : REUSE :: HEIRLOOM : _______", options: ["Inherit", "Keep", "Save", "Value"], answer: "Inherit", explanation: "A palimpsest involves reuse; an heirloom involves inheritance." },
    { question: "INDELIBLE : ERASE :: INEFFABLE : _______", options: ["Utter", "Speak", "Say", "Hear"], answer: "Utter", explanation: "Indelible cannot be erased; ineffable cannot be uttered/described." },
    { question: "ICONOCLAST : TRADITION :: ANARCHIST : _______", options: ["Government", "Law", "Rule", "State"], answer: "Government", explanation: "Iconoclast attacks tradition; anarchist attacks government." },
    { question: "PANEGYRIC : PRAISE :: ELEGY : _______", options: ["Lament", "Sadness", "Death", "Cry"], answer: "Lament", explanation: "Panegyric is a speech of praise; elegy is a poem of lament." },
    { question: "INTRANSIGENT : FLEXIBILITY :: STOLID : _______", options: ["Emotion", "Feeling", "Movement", "Action"], answer: "Emotion", explanation: "Intransigent lacks flexibility; stolid lacks emotion." },
    { question: "DESICCATE : MOISTURE :: DARKEN : _______", options: ["Light", "Sun", "Bright", "White"], answer: "Light", explanation: "Desiccate removes moisture; darken removes light." },
    { question: "PULCHRITUDE : BEAUTY :: INDOLENCE : _______", options: ["Laziness", "Sleep", "Slow", "Rest"], answer: "Laziness", explanation: "Pulchritude is beauty; indolence is laziness." },
    { question: "DIAPHANOUS : OPAQUE :: LIMPID : _______", options: ["Murky", "Clear", "Dark", "Cloudy"], answer: "Murky", explanation: "Diaphanous is opposite of opaque; limpid (clear) is opposite of murky." },
    { question: "APOSTATE : RELIGION :: TRAITOR : _______", options: ["Country", "Team", "Friends", "Family"], answer: "Country", explanation: "Apostate betrays religion; traitor betrays country." },
    { question: "QUIXOTIC : IDEALISTIC :: MACHINATION : _______", options: ["Plotting", "Planning", "Thinking", "Doing"], answer: "Plotting", explanation: "Quixotic means idealistic; machination means plotting." },
    { question: "AMELIORATE : IMPROVE :: OSSIFY : _______", options: ["Harden", "Soften", "Break", "Fix"], answer: "Harden", explanation: "Ameliorate means to improve; ossify means to harden." },
    { question: "OBFUSCATE : CLARITY :: ENERVATE : _______", options: ["Energy", "Strength", "Power", "Life"], answer: "Energy", explanation: "Obfuscate reduces clarity; enervate reduces energy." },
    { question: "EXCULPATE : BLAME :: EXTIRPATE : _______", options: ["Destroy", "Build", "Create", "Make"], answer: "Destroy", explanation: "Exculpate removes blame; extirpate destroys completely." },
    { question: "EQUIVOCATE : DECEIVE :: FILIBUSTER : _______", options: ["Delay", "Stop", "Prevent", "Block"], answer: "Delay", explanation: "Equivocate is used to deceive; filibuster is used to delay." },
    { question: "MAVERICK : CONFORMITY :: HERETIC : _______", options: ["Orthodoxy", "Belief", "Faith", "Church"], answer: "Orthodoxy", explanation: "Maverick opposes conformity; heretic opposes orthodoxy." }
  ]
};

